### ISSUE TITLE
AudioIn.stop() may be not be working for newer browser versions

### ISSUE THREAD

**Issue by abhagat** [processing/p5.js-sound#105]
When calling `stop()` for an `AudioIn` object, I received the following error in Chrome 49:
 
>Uncaught TypeError: this.stream.stop is not a function

In Firefox 46.0.1:
>MediaStream.stop() is deprecated and will soon be removed. Use MediaStreamTrack.stop() instead.

This likely corresponds to [MediaStream.stop() has been deprecated (Firefox)](https://www.fxsitecompat.com/en-CA/docs/2015/mediastream-stop-has-been-deprecated/) and [MediaStream Deprecations (Chrome)](https://developers.google.com/web/updates/2015/07/mediastream-deprecations?hl=en). [Other projects](https://github.com/meetecho/janus-gateway/issues/363) suggest that this was removed in Chrome M47.

I think this is a small fix from:
```
  p5.AudioIn.prototype.stop = function() {
    if (this.stream) {
      this.stream.stop();
    }
  };
```

to 

```
  p5.AudioIn.prototype.stop = function() {
    if (this.stream) {
      this.stream.getTracks().forEach(function(track) {track.stop()});
    }
  };
```

I attempted to make this change myself, but I wasn't able to get mocha up and running.

**Comment by DigitalWheelie** [comment]
I get similar issues w/ AudioIn, but it doesn't work for me at all in Chrome (Mac Version 49.0.2623.110 (64-bit)), not even the P5 demo page:
http://p5js.org/reference/#/p5.AudioIn

The error I get is:
NavigatorUserMediaError {name: "PermissionDeniedError", message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", constraintName: ""}

**Comment by abhagat** [comment]
Your case may be slightly different - change it to using https and see how it goes?

**Comment by lmccart** [comment]
more details from @DigitalWheelie's original issue here: https://github.com/processing/p5.js/issues/1340#issuecomment-204747662

**Comment by abhagat** [comment]
@DigitalWheelie Tried this on the latest version of Chrome. For your issue, using https, not http, will allow you to give the browser permission to use your microphone. Chrome [will not allow using unsecure origins](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia), even for the non-deprecated method `navigator.mediaDevices.getUserMedia`. This is to [prevent attackers from listening to a user's microphone](http://stackoverflow.com/a/34198101). 

The documentation page you're referencing probably needs to handle the case where the user refuses to grant permission to use the microphone - or if the page is otherwise unable to get permission from the user. This is possible via an error callback on `AudioIn.start()`.

Separately, the top-issue on the thread, `AudioIn.stop()` is flat-out broken, not deprecated, in Chrome, due to changes in the `MediaStream` API.

**Comment by abhagat** [comment]
@therewasaguy Looks good, thanks.
