### ISSUE TITLE
WAV file is not downloaded with correct playback rate

### ISSUE THREAD

**Issue by enjikaka** [processing/p5.js-sound#107]
```
// sample = p5 SoundFile
sample.playMode('restart');
sample.play();
sample.rate(1.4142135623730951);
```

`saveSound(sample)` will download the sample with a very low playback rate, even lower than the original. All files I've tested and exported runs at 0.458 of the original playback rate. Doesn't matter if you set the range or not.

Something wrong in the creation of WAV-files?

**Comment by therewasaguy** [comment]
Hi @enjikaka, in this code snippet, you're changing the playback rate of the audio data in the context of your sketch, without modifying the original sound file. The saveSound method doesn't record any changes. If you want to record the live output of your audio processing to a soundfile, you can do that using the [p5.SoundRecorder](http://p5js.org/reference/#/p5.SoundRecorder). In that example, you'd use the `setInput(sample)` method to tell the recorder what to listen to.

**Comment by enjikaka** [comment]
So you can not have a flow like this?

Open file > Select pitch > Download file

If a recorder step is needed, that is so bad. Imagine that file is a 3
minute MP3...

Den tors 7 apr. 2016 02:11Jason Sigal <notifications@github.com> skrev:

**Comment by therewasaguy** [comment]
@enjikaka It is possible to do this with the Web Audio API's offline audio context:

https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext

>> In contrast with a standard AudioContext, an OfflineAudioContext doesn't render the audio to the device hardware; instead, it generates it, as fast as it can, and outputs the result to an AudioBuffer.

But, so far, p5.sound exists only in the standard AudioContext.

**Comment by enjikaka** [comment]
Ah, okey. I'll try something with that then. Thanks!

Den tors 7 apr. 2016 20:48Jason Sigal <notifications@github.com> skrev:
