### ISSUE TITLE
"MediaStreamTrack.getSources is deprecated" error in chrome 49.0.2623.87

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#109]
reposting from @adamforbes (https://github.com/processing/p5.js/issues/1352):

When loading p5.sound.js, i receive the error "MediaStreamTrack.getSources is deprecated. See https://www.chromestatus.com/feature/4765305641369600 for more details."

Are there any plans to move this over to MediaDevices.enumerateDevices()?

**Comment by startexploding** [comment]
same error here.

**Comment by chadxsmith** [comment]
same here!

**Comment by polyrhythmatic** [comment]
I wrote a lot of the original get sources functionality so I can look into this.  I'll assign myself!

**Comment by podrivo** [comment]
Same here!

**Comment by therewasaguy** [comment]
https://github.com/processing/p5.js-sound/pull/160
