### ISSUE TITLE
p5js sound whileLoadingCallback

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#115]
reposting from @setupandraw (https://github.com/processing/p5.js/issues/1358)

Hi there,

I am working on a small project in P5js including video and sound and I was wondering how I can create a simple preloading showing loaded percentage of the video/audio files.

I saw there are very few info in the P5js.org reference about this topic.
Es. for the sound library:

new p5.SoundFile(path,[successCallback],[errorCallback],[whileLoadingCallback])

[whileLoadingCallback] // Function: Name of a function to call while file is loading. That function will //receive percentage loaded (between 0 and 1) as a parameter.

But this is not enough for my poor coding skills to understand how I can actually use that… 
What if I just want the whileLoadingCallback function and not the errorCallback?
How can I use the percentage loaded received by the whileLoadingCallback function?

Any examples?

Thank you very much!

**Comment by therewasaguy** [comment]
Hi @SetupandDraw, thanks for bringing this up. There was an issue with `whileLoading` that I have fixed. Feel free to try it with [this version of the library](https://raw.githubusercontent.com/processing/p5.js-sound/master/lib/p5.sound.js) and here's an example using it without an errorCallback:

```
function setup() {
  soundFile = loadSound('beat.mp3', soundReady, null, whileLoading);
}

function whileLoading(total) {
  print('loaded: ' + total);
}

function soundReady() {
  print('sound is ready')
}
```

It's important to point out that the `total` only reflects the progress of the request to load the file's data. It doesn't include the additional time that it takes for the Web Audio API to [decodeAudioData](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/decodeAudioData). That can take about as long as the request itself. So until we can get a similar progress event from decodeAudioData, the whileLoadingCallback really only gets us 50% of the way to a loaded sound. I'm debating whether to figure out the right place to add this to the docs, or to remove the whileLoading callback, if you have any insight I'd be curious to hear whether it's useful for you.
