### ISSUE TITLE
SoundFile docs are inconsistent.

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js-sound#118]
(Transferred from p5js issue)
In the description we have:
"Values less than zero will reverse the audio buffer."
In the parameter we have
" Must be greater than zero."

Negative values appear to work for me, but I don't know which is the correct behaviour so I am opening this issue so someone who knows can fix it.

**Comment by therewasaguy** [comment]
Good call, @meiamsome! Updated in the library, and soon this will be reflected in the online docs
