### ISSUE TITLE
SoundFile currentTime() drifting?

### ISSUE THREAD

**Issue by jfred1979** [processing/p5.js-sound#120]
On Chrome  51.0.2704.103 m on Windows 10:

`console.log(getAudioContext().currentTime - someSoundFile.currentTime());`

in the draw loop results in the following output:

2.49188582356771
2.49275244140625
2.49671915690104
2.49845247395833
2.49931917317708
2.500119140625
2.50321915690104
2.50495247395833
...

and so on, continuously getting larger. In theory, shouldn't this stay consistent as long as the SoundFile playback is not interrupted?

**Comment by therewasaguy** [comment]
Hi @jfred1979, is this happening while a file is playing or paused? If it's paused, then that would make sense because AudioContext.currentTime is always increasing.
