### ISSUE TITLE
Is it possible to control p5.Filter frequency with a p5.Oscillator?

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#126]
reposting via @JoshuaStorm (https://github.com/processing/p5.js/issues/1541)

Just a question:

Hi, sorry if this is a question better asked elsewhere, but:

I want to make a oscillator modulated filter (a la LFO->FilterFreq). Doing something similar with one Oscillator modulating another Oscillator's frequency was fairly straightforward:

var lfo = p5.Oscillator();
sawOsc.freq(lfo);
but doing

filter.freq(lfo);
Does not seem to do anything? Is this functionality just not implemented? Thanks!

**Comment by JoshuaStorm** [comment]
Looking at the source, it does not seem that this is currently supported, but looking into the WebAudioAPI this seems entirely possible.

When I have a chance, I'll have a stab at this, so hopefully I'll have a PR up for this soon! :smile:

**Comment by therewasaguy** [comment]
@JoshuaStorm thanks for bringing this up. I just looked at the source and did a test to confirm that this will work the same for filter.freq() as for osc.freq(). But if LFO's amplitude is within the default range of +1 -1, we don't perceive the difference in frequency. If you increase the LFO's amplitude, it will be more obvious. Here's an example:

```
var lfo, osc, filter;

function setup() { 
  createCanvas(400, 400);

	lfo = new p5.Oscillator();
	osc = new p5.SawOsc();
	filter = new p5.Filter();

	// chain
	lfo.disconnect();
	osc.disconnect();
	osc.connect(filter);

	lfo.start();
	osc.start();

	lfo.freq(0.5);
	osc.freq(400);
	filter.freq(1200);

	filter.res(24);
	// how many Hz should the LFO oscillate
	lfo.amp(1100);
	

	// connect the lfo
	filter.freq(lfo);
} 

```

Let me know if that doesn't work for you or if you have ideas for how to improve this type of functionality, a PR would rule!

**Comment by JoshuaStorm** [comment]
Oops, I definitely glossed over that line in the source, I see it now. My bad!

I must have made some mistake in how I did this in my project, when I get a chance I'll give it another shot and report back.

Regardless, the doc for this is missing a bit since it only shows `freq()` method as having a number param, I'll put up a PR for that soon. 

While we are on the topic, is there any reason there is no distortion in p5? WebAudioAPI has the `WaveShaperNode` which I imagine would be a welcome addition to p5. If there is no reason not to, I'll gladly give it a shot!

**Comment by JoshuaStorm** [comment]
Sorry for the delay, but trying this again in my project I have confirmed it is definitely a problem on my end.

Hopefully I can figure that out soon, but this is definitely good to be closed.

**Comment by therewasaguy** [comment]
Thank you @JoshuaStorm. Distortion would be a fun addition if you want to give it a shot. Curious what you have in mind for that, feel free to make a new issue for it

**Comment by daniloprates** [comment]
hey @therewasaguy thanks for this tip. I'm making an [experimental project](https://daniloprates.github.io/redux-synth/) using p5 sound to study React and Redux and it work very fine. 

(mute your computer before clicking, for some reasons it gets some feedback loops sometimes :/ )
