### ISSUE TITLE
master.js - DynamicsCompressor.ratio.value 100 outside nominal range [1, 20]

### ISSUE THREAD

**Issue by JoshuaStorm** [processing/p5.js-sound#130]
Found this issue: It seems to have been reported and closed in #123 with no comments or references.

Just importing p5.js I get this warning being thrown:

`DynamicsCompressor.ratio.value 100 outside nominal range [1, 20]; value will be clamped.`

I have found this in the latest [WebAudioAPI docs](https://webaudio.github.io/web-audio-api/#widl-DynamicsCompressorNode-ratio)

>The amount of dB change in input for a 1 dB change in output. Its default value is 12. Its nominal range is [1, 20].

Just to be clear, there is no issue (for me at least) arising from this aside from the warning being thrown.

**Comment by therewasaguy** [comment]
I guess a ratio of 100 is excessive and impossible. Quick fix by changing [this line](https://github.com/processing/p5.js-sound/blob/master/src/master.js#L15) to 20. @JoshuaStorm did you want to send a pr for this?
