### ISSUE TITLE
p5.soundOut reference page not loading

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#134]
reposting via @zoebachman https://github.com/processing/p5.js/issues/1595:
The p5.soundOut link on the p5 Sound Library reference page says it can't be found and redirects to the general reference.

**Comment by therewasaguy** [comment]
Hmm, the issue seems to be the period in `p5.soundOut`. One possible solution is to add it to the prototype and then documentation would be about soundOut rather than p5.soundOut.
