### ISSUE TITLE
Unable to use p5.sound.js as an npm library

### ISSUE THREAD

**Issue by JasoonS** [processing/p5.js-sound#137]
I would like to know how to use the sound library in the p5 npm module. I know the code is in there in a sub-folder called 'addons', but don't know how to import or use it.

Currently I have 
`import p5 from 'p5'` 
and that works completely fine, I can do all the standard p5 things. But I have not been able to get it to work for any of the sound libraries. 

Using the files directly from the p5js.org website
`import p5 from './p5/p5.js'`
works completely fine. But I have had no success with
`import Oscillator from './p5/addons/p5.sound'`  (or other such variants).

Any help will be greatly appreciated!

**Comment by JasoonS** [comment]
I found the solution! It's very simple. The following should do the trick.

import 'p5/lib/addons/p5.sound';
import 'p5/lib/addons/p5.dom';

**Comment by ccorcos** [comment]
documentation!

**Comment by ccorcos** [comment]
didnt work for me

**Comment by theonlyjames** [comment]
Didn't work for me either.

**Comment by ccorcos** [comment]
I got it to work like this:

https://github.com/ccorcos/circle/blob/master/src/sketch.js

**Comment by theonlyjames** [comment]
That worked perfectly :) for p5.dom as well. Thanks! @ccorcos

**Comment by conc2304** [comment]
I found a somewhat hacky solution.
My issues was that p5 was not defined when loading the p5 sound module.
So after googleing the entire internet with no solution, I decided to try something dumb.
I added `import p5 from "p5";` to the top of "p5/lib/addons/p5.sound";

then imported them as normal
`import p5 from "p5";
import "p5/lib/addons/p5.sound";
`

and it's working so far

**Comment by j23saw** [comment]
Can you explain how did you add them in the script tag?

**Comment by h4k1m0u** [comment]
I confirm that adding `import p5 from "p5";` to `p5/lib/addons/p5.sound` allowed to get rid of that error in gulp too, but I wonder whether this problem will be fixed in future versions.

**Comment by tobidot** [comment]
I used parcel + typescript and had the same issue,
but i think it works fine with the following

```
import "p5";
(<any>window).p5 = p5;
import 'p5/lib/addons/p5.sound';
```

since the problem is p5.sound tries to extend the class p5,
wich with bundlers is named something like p5_1 and thus tries to access and empty object.
Adding p5 to the global scope should solve it.
(If you are not using typescript simply remove the '<any>')

**Comment by h4k1m0u** [comment]
> (<any>window).p5 = p5;

It doesn't seem to work if the js code is inside an external file (`app.js`) as `window` is undefined in that case.

**Comment by j23saw** [comment]
I downgraded to 0.9 and then it seems to work fine

**Comment by tobidot** [comment]
> > (window).p5 = p5;
> 
> It doesn't seem to work if the js code is inside an external file (`app.js`) as `window` is undefined in that case.

Unless you are trying to run on node.js window should always be defined, as far as i am aware (and in node you could use the global.p5, though p5 seems a little useless in a node env to me ).

Or did you meant to say 'p5' is undefined and you cannot add code between those two import line.

**Comment by nuc** [comment]
That can be easily solved by using webpack's [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/):

```js
  plugins: [
    new webpack.ProvidePlugin({
      p5: 'p5'
    })
  ]
```
