### ISSUE TITLE
p5sound part::onStep - doesn't loop

### ISSUE THREAD

**Issue by kimon-satan** [processing/p5.js-sound#151]
When using onStep in conjunction with loop, the call back stops after the first iteration.

Please see the snippet below ...

<code>
var click, myPart, myPhrase;
var myPat = [1,0,0,2,0,2,0,0];

function preload()
{
  click =  loadSound("assets/click.mp3");
}

function setup()
{

  myPhrase = new p5.Phrase('click', playClick, myPat);
  myPart = new p5.Part();
  myPart.addPhrase(myPhrase);
  myPart.setBPM(60);
  myPart.onStep(function(){
    //only seven values are outputted to the console
    console.log(frameCount);
  })

  myPart.loop();
}

function playClick(time, playbackRate) {
  click.rate(playbackRate);
  click.play(time);
}
</code>

**Comment by b2renger** [comment]
@kimon-satan 

it works for me are you sure you are using the latest p5.sound version ? (I tested it on openprocessing)

**Comment by b2renger** [comment]
@cfboyd , I do it like that

```javascript
var myPart 
var beat = 0 
var bpm = 90 

function setup() {
    myPart = new p5.Part();  
    var pulse = new p5.Phrase('pulse', step, [1, 1, 1, 1]);
    myPart.addPhrase(pulse); // on ajoute notre phrase à l'objet part
    myPart.setBPM(bpm);
    myPart.start();
    myPart.loop();
}

function step() {
   beat = beat +1
}
```
I have an example for a small step-sequencer that uses this technique you can check it out here : https://b2renger.github.io/Introduction_p5js/07_audio_02_stepsequencer/index.html

**Comment by cfboyd** [comment]
thanks that totally fixed my issue!
