### ISSUE TITLE
How to retrieve the sound data for upload

### ISSUE THREAD

**Issue by SirCameron** [processing/p5.js-sound#157]
Great project!

I have one request, though, which is to have the ability to retrieve the wav file data without saving to a file. I would like to upload the data directly to a server.

Another issue is that in the documentation, the saveSound function is in the SoundRecorder object, yet in the examples the standalone function "save" is called. SoundRecorder.saveSound in undefined. Am I missing something here?

Note: I'm using this in a node environment with react.

**Comment by analizabongat** [comment]
any update here?

**Comment by b2renger** [comment]
@SirCameron @analizabongat 

you could try use the _getBuffers()

https://github.com/processing/p5.js-sound/blob/master/src/soundRecorder.js#L213

maybe this function should be exposed and documented.

**Comment by Tremerit** [comment]
Can someone give an example of this working, I require exactly the same thing as they do, actually. 
I have a website and I need to work out how to save recordings on to a database, like firebase.

**Comment by Tremerit** [comment]
@SirCameron @b2renger @analizabongat 

Have any of you found a way that definitely works, yet?

**Comment by hebrao** [comment]
I need upload audio recorded to a server (without user interference). 
Anyone?

**Comment by therewasaguy** [comment]
Please check out the `getBlob` method which has been added recently https://p5js.org/reference/#/p5.SoundFile/getBlob

I hope this isn't way too late to be helpful !
