### ISSUE TITLE
Playing an Oscillator in draw, does not work properly

### ISSUE THREAD

**Issue by Hussein-Ben** [processing/p5.js-sound#164]
The problem is that by playing an oscillator in draw, you start overwriting the sound and eventually the sound dies out. 

Is it possible the warn users not call any oscillator in draw?

[https://p5js.org/reference/#/p5.Oscillator](url)
preferably  in the description section

thanks.

**Comment by therewasaguy** [comment]
@Hussein-Ben can you provide an example?
