### ISSUE TITLE
Feature Request: p5.Oscillator missing getPhase() or getValue()

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#167]
_From @hepiyellow on April 15, 2017 17:30_

I am missing the ability to sample the current value of an oscillator.
Either the value or the phase.

This would allow to make visuals which are synced to the sound.
For example a Freq modulation oscillator , and visuals which modulate in-sync would be very nice to have. I think it is the basic of good audio-visual creations. 

_Copied from original issue: processing/p5.js#1895_

**Comment by b2renger** [comment]
@hepiyellow ?

What are you looking for exactly ?  Doesn't those examples cover this use case ?
https://p5js.org/examples/sound-measuring-amplitude.html
https://p5js.org/examples/sound-oscillator-frequency.html
https://p5js.org/examples/sound-frequency-spectrum.html

on most of those function you can pass the size of the buffer you want to analyse. To get a sample accurate value you'd have to run your sketch at an impossible to achieve framerate. 
Audio rate is 44100 samples per seconds, optimal sketch framerate is 60 frame per second. 
So you need to do the analysis on a chunck of samples each frame and you can play on this buffer size to have something more responsive (with a small buffer - heavier on ressources) or something more based on averaged values (bigger buffer - easier on ressource but can introduce latency issues).

Let me know if it helps

**Comment by hepiyellow** [comment]
Is this possible?

a= new p5.Amplitude();
a.setInput(new p5.TriOsc());

**Comment by b2renger** [comment]
Yes :) of course !

you may want to create a seperate variable for you oscillator though but yes definitely

**Comment by aatishb** [comment]
In case it helps anyone else, osc.f and osc.output.gain.value will give you the frequency and amplitude of an oscillator osc.

**Comment by aatishb** [comment]
.. and osc.phaseAmount gives you the phase. Looks like this can be closed.

**Comment by lmccart** [comment]
thanks @aatishb!
