### ISSUE TITLE
p5.sound Delay On Chrome crash audio of tab on Feedback change

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#168]
_From @davidrop on April 23, 2017 16:2_

Hi all, 
P5 is great...

i found a bug that happen only on Chrome, not on firefox, didn't test on other browser

if i change delay feedback while delay is processing, the entire tab stop emit sound

i wrote this script to test
https://www.davidrop.com/testdelay/

you have 3 slides that work in little different ways, all 3 slides works as intendeed on firefox. 

slide 1)  disconnect, modify feedback, reconnect
slide 2)  modify feedback without disconnect
slide 3)  disconnect, destroy the p5.Delay object, recreate the object, reconnect

this bug happen only with delay feedback, i tested filter, delay, reverb and distortion and i can update all parameters without any bug both on firefox and chrome.  

Good Work

_Copied from original issue: processing/p5.js#1909_

**Comment by therewasaguy** [comment]
Related: https://github.com/processing/p5.js-sound/issues/139

**Comment by davidrop** [comment]
Version v0.3.3 2017-01-28 fix this!!!!
but sometimes this bug still happens if you use a minified version "p5.sound.min.js"

**Comment by montoyamoraga** [comment]
because of the latest comment that celebrates that the issue was mostly fixed,
and because of how much the library and the browsers have changed since 2017,
i am closing this issue for now ~
