### ISSUE TITLE
safari 10.1 raises "this browser does not support AudioIn" error --> Better error handling (defaults + documentation)

### ISSUE THREAD

**Issue by tinydeltas** [processing/p5.js-sound#171]
I am working on a sketch which requires microphone input, but when I test it in the Safari browser shipped with macOS 10.12, I get this error. What should I be doing differently? 

The entirety of my p5 sound code is : 

```
	mic = new p5.AudioIn();
	mic.start();
```

**Comment by aatishb** [comment]
I'm having the same issue. See e.g. [this link](https://aatishb.com/experiments/chromaticspiral/) which works fine in Chrome.

**Comment by therewasaguy** [comment]
Unfortunately Safari doesn't support WebRTC (`getUserMedia`) or Web Media Capture and Streams API's (`MediaStreamTrack`). These APIs are necessary to access the user's microphone on Safari in JavaScript/Web Audio. Without native browser support for these API's, it's only possible with browser plugins.

It is possible to provide an error handler when creating the AudioIn that will do something more elegant than showing that alert
https://github.com/processing/p5.js-sound/blob/master/src/audioin.js#L24

But this leads to confusion for people working with the library. And the alert might not be the best default user experience.

How can we make this better?

**Comment by aatishb** [comment]
Thanks for looking into this. Looks like Safari 11 will support WebRTC. https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html

**Comment by montoyamoraga** [comment]
closing this issue because of the changes that must have happened since 2017 ~
