### ISSUE TITLE
setVolume rampTime and timeFromNow arguments do not produce any effect

### ISSUE THREAD

**Issue by rjbultitude** [processing/p5.js-sound#174]
I understand that setVolume's `rampTime` and `timeFromNow` are available to optionally create a fade on the chosen sound. However, any numeric values I use for these arguments have no effect. 
Having tested and logged the vars used inside the method it seems that the linearRampToValueAtTime calls effectively just override the default volume. Perhaps I've misunderstood how it's supposed to be used but I added a couple of new arguments (for attack and decay) and it works perfectly. I've created [a Gist with the modified method here](https://gist.github.com/rjbultitude/279fc4758ee6059a2159d9f63c0af758). 
Which would be used like so:
Attack
`dropSound.setVolume(0.6, 0.5, 0.01, 0.1);`
Decay
`dropSound.setVolume(0.6, 0.5, 0.01, null, 0.1);`
If it's a sensible fix then I'm happy to create a PR.

**Comment by endurance21** [comment]
@rjbultitude can you ease give a brief of your gist?..

**Comment by rjbultitude** [comment]
Hi @endurance21 

This issue can be closed. 

I can't recall whether it was a temporary bug or an issue with my code but having tried it in the [SoundFile](https://p5js.org/reference/#/p5.SoundFile) example it works fine. 

Perhaps it was just that it wasn't clear that the method needs to be called twice: once to set the initial volume and then again to ramp up/down to a new volume.

**Comment by endurance21** [comment]
@rjbultitude  you can close the issue by yourself, if you feel so !
