### ISSUE TITLE
strange echo in Chrome for mac Os, Crash for Chrome on Android

### ISSUE THREAD

**Issue by swirly** [processing/p5.js-sound#180]
Hello

A very simple use of p5sound leads to a strange behavior
The code is straight :
* preload
* play
* loop
that's all

inclusion of librarie in html : 
----
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/p5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/addons/p5.sound.min.js"></script>

----

Use of the librarie
----
function preload() {
    song = loadSound("Money.mp3")
}

function setup() {
    //partie sonore
    song.setVolume(0.5)
    song.play()
    song.loop()
.....
}

------

You can watch it there :
http://icn.lec.ac-grenoble.fr/travaux/2016-2017/04/money.html

On Mac Os X,
On Firefox, no problem
On Chrome, the sound is played with an echo. 
It crashes Chrome on Android

If I use chrome to read MP3 file directly with URL
http://icn.lec.ac-grenoble.fr/travaux/2016-2017/04/Money.mp3

There is no echo, so it's not a chrome related problem 

Hope this reports helps

**Comment by swirly** [comment]
OK
Find the reason
play and loop launch two times the playback. Except it works differently in firefox and Chrome !
May be it's just a minor documentation clarification to have : loop launches playback :)

**Comment by montoyamoraga** [comment]
per the last comment, that it is a minor documentation clarification, i am closing this issue ~
