### ISSUE TITLE
SoundFile.setVolume() has no effect

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js-sound#182]
You can see this by simply changing the volume in the [SoundFile](https://p5js.org/reference/#/p5.SoundFile) example, as below: 
```

function preload() {
  mySound = loadSound('assets/doorbell.mp3');
}

function setup() {
  mySound.setVolume(0); // changed from 0.1
  mySound.play();
}
```

**Comment by nbrosowsky** [comment]
I ran into the same issue. The workaround for me was to manipulate the volume using the "amp" parameter passed to the play function (see issue #144 ).

The play function takes a number of additional parameters:

`p5.SoundFile.prototype.play = function (time, rate, amp, _cueStart, duration)
`

So in your example, you could do something like this (Note that you'll need to set the time (0 = now), and rate (1 = normal playback) in addition to the amplitude): 

```
function preload() {
  mySound = loadSound('assets/doorbell.mp3');
}

function setup() {
  mySound.play(0, 1, 0.1);
}
```

Unfortunately, this created an additional problem where the first playthrough of the audio sample was not adopting my set volume. This is related to some code in p5.sound.js (line 1065) that sets the default amp to 1:

`var a = amp || 1`

So, I edited the js file to remove the OR statement and now it works fine. 

e.g., 
line 1065: `var a = amp`

Though, now obviously everytime you run the play() function you need to pass an amp parameter. 

Also, setting the volume through this method does not allow you to take advantage of the ramp time that setVolume had. So it's still not ideal but got me moving forward.

I'll also add, that once you've set the amp parameter and the sound is playing, you can manipulate the volume using the mySound.setVolume() function. So you could fade the sound out, once it has started.

**Comment by dhowe** [comment]
Thanks @nbrosowsky, very thorough. But this is such a basic function, I'm not sure we should be teaching students using this library. Perhaps it should be labelled as 'alpha' or not-ready-for-production? Are there other JS sound libraries people are using with p5.js?

**Comment by nbrosowsky** [comment]
I've just started using P5.js, so I'm fumbling my way through it! 

After looking into it a little more, a simpler and (I think) more permanent solution is to change the default amp to the current gain of the soundFile:

line 1065: `var a = amp || this.output.gain.value;`

Every time you hit play the default was overriding whatever the current gain setting was. With this change, you can use setVolume() as intended and the gain will be preserved when you hit play.

As for other JS sound libraries. I know [HoweverJS](https://howlerjs.com/) is one that has been around for a while. 

As an audio playback library, Howler has some nice functionality that P5.Sound does not (e.g., audio sprites, playback event listeners) and has a nice simple API. Though, there are tradeoffs. Howler does not have the same timing/syncing capabilities (e.g., phrases/parts/scores) or sound manipulation tools (e.g., reverb, distortion etc.).

**Comment by b2renger** [comment]
@nbrosowsky thanks for the investigation would you like to create a pull-request for your fix ?

@dhowe there are many other audio libs (mainly Tone.js on which p5.sound is heavily based), but p5.sound is by far the simplest + it can be used with other lib. 

So I think we should fix this setVolume issue as per every issue and I think there is really no need to "label" the library as alpha, web audio api breaks often with update to browsers - but it's more about the state of audio on the web rather than anything else.

**Comment by therewasaguy** [comment]
@nbrosowsky looks like a good solution! Another solution might be to just use the setVolume method in `play`

Let me know if you are already working on this, if not I will do it as I need to refactor the soundfile module.

**Comment by nbrosowsky** [comment]
Sorry, I didn't get a chance to do this. 

Thanks for taking care of it!

**Comment by kino2007** [comment]
why not
soundFile.play( parameters );
soundFile.stop( parameters ); //immediately stop.
soundFile.play( parameters ); //immediately play again
hopefully this is what u mean

**Comment by faxinadu** [comment]
thanks for this fix, confirmed here this produces intended behavior
