### ISSUE TITLE
soundFile.pan() does not pan 100%

### ISSUE THREAD

**Issue by nbrosowsky** [processing/p5.js-sound#189]
There seems to be an issue with the pan method in p5.sound. Panning left or right using -1 to 1 does not pan 100% to the left or right speaker. Despite being fully panned you can still hear the sound in the other speaker. 

This is the case even in your demo (https://p5js.org/reference/#/p5.SoundFile/pan). 

I tested this on my macbook using the latest Chrome and Firefox, also tried it on Windows 10, Chrome.

Is there a way to get sounds 100% in one, and 0% in the other?

**Comment by nbrosowsky** [comment]
It turns out the pan is working properly and does pan 100%. However, if you call on soundFile.pan() within the playback of a phrase, it won't completely pan on the first playthrough unless you specify the time parameter, which in the case of a looped phrase/part is the variable "time".

As per this example:
```
var box, drum, myPart;
var boxPat = [1,0,0,2,0,2,0,0];
var drumPat = [0,1,1,0,2,0,1,0];
var msg = 'click to play';

function preload() {
  box = loadSound('assets/beatbox.mp3');
  drum = loadSound('assets/drum.mp3');
}

function setup() {
  noStroke();
  fill(255);
  textAlign(CENTER);
  masterVolume(0.1);

  var boxPhrase = new p5.Phrase('box', playBox, boxPat);
  var drumPhrase = new p5.Phrase('drum', playDrum, drumPat);
  myPart = new p5.Part();
  myPart.addPhrase(boxPhrase);
  myPart.addPhrase(drumPhrase);
  myPart.setBPM(60);
  masterVolume(0.1);
}

function draw() {
  background(0);
  text(msg, width/2, height/2);
}

function playBox(time, playbackRate) {
  box.rate(playbackRate);
  box.play(time);
}

function playDrum(time, playbackRate) {
  drum.rate(playbackRate);
  drum.play(time);
}

function mouseClicked() {
  if (mouseX > 0 && mouseX < width && mouseY > 0 && mouseY < height) {
    myPart.start();
    msg = 'playing part';
  }
}
```

If you want to pan the beatbox soundFile within the playBox function "time" needs to be specified for it work properly:
```
function playBox(time, playbackRate) {
  box.pan(-1, time);
  box.rate(playbackRate);
  box.play(time);
}

```

**Comment by therewasaguy** [comment]
Thanks @nbrosowsky 

`time` should be passed into all scheduled events like you have described in your second comment. I'm not sure if there is a way around that when working with web audio and scheduled events. Feel free to reopen this if you want to find a way to make that work. And/or if you are finding that [this example](https://p5js.org/reference/#/p5.SoundFile/pan) is not panning 100%, but it sounds like it is working as expected.
