### ISSUE TITLE
Uploading soundFile to Server 

### ISSUE THREAD

**Issue by ismail13j** [processing/p5.js-sound#211]
i have to store the soundFile into my Server, I searched all over the P5.js site but couldn't found anything helping ... please provide me with solution if u have ..... Thanks

**Comment by hebrao** [comment]
Did you find a way to do that?
I need upload my audios too... :(

**Comment by ismail13j** [comment]
@hebrao feeling sorry to inform that i failed to find solution to upload audio File to server using P5.js

**Comment by iFlameing** [comment]
I started working on this issue :)

**Comment by bmoren** [comment]
https://discourse.processing.org/t/uploading-recorded-audio-to-web-server-node-js-express/4569

**Comment by montoyamoraga** [comment]
solved per the last comment, so i am closing it ~
