### ISSUE TITLE
p5.sound.js as module in webpack. p5sound initialization is not fully extending p5

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#212]
_From @Izzaki on August 12, 2017 18:40_

Hello,
Im using p5 instance against global accessing.
My angular4 app (webpack) doesn't merge p5.sound addon with p5 fully.
At some point i can use p5.sound extended functions like p5.loadSound();
but i can't use p5.FFT and many more.

Should i include p5.sound in different way?
Or is it p5.sound modularity issue?

#### Nature of issue?

- [ ] maybe found a bug
- [ ] or new feature request

#### Most appropriate sub-area of p5.js?

- [ ] p5.sound

#### Which platform were you using when you encountered this?

- [ ] Desktop/Laptop

#### Details: 

version: p5.js v0.5.11 June 01, 2017
framework: angular4

	import * as p5module from 'p5/lib/p5';
	import * as p5moduleSound from 'p5/lib/addons/p5.sound';

	constructor(){
		var p5start = function(p5){

		/**
		@p5moduleSound is an empty object, but putting it here is like calling the module
		- so at this point, this just extends p5 object.
		*/
		p5moduleSound;
		
		var song = null;
		var fft = new p5.FFT(0, 20); // p5.FFT is UNDEFINED!
		
		p5.preload = function() {
			song = p5.loadSound('assets/song.mp3'); // works well!
		}
		
		p5.setup = function() {
			p5.createCanvas(400, 200);
		}

		p5.draw = function() {
			p5.background(125, 0);
		};
		var p5instance = new p5module(p5start, 'music-visualizator');
 	}

_Copied from original issue: processing/p5.js#2117_

**Comment by tasiek** [comment]
As noticed in [some other issue](https://github.com/processing/p5.js-sound/issues/137), you should import it like that:

```javascript
import p5 from 'p5';
import 'p5/lib/addons/p5.sound';
```
then you can use `p5.FFT` and others.

**Comment by TiredFalcon** [comment]
This is not working for me
I get this error:
```
Uncaught ReferenceError: p5 is not defined
    at Object.eval (p5.sound.js?e617:3112)
    at Object.eval (p5.sound.js?e617:3160)
    at __webpack_require__ (p5.sound.js?e617:84)
    at Object.eval (p5.sound.js?e617:2885)
    at Object.eval (p5.sound.js?e617:2956)
    at __webpack_require__ (p5.sound.js?e617:84)
    at eval (p5.sound.js?e617:120)
    at eval (p5.sound.js?e617:122)
    at Object../node_modules/p5/lib/addons/p5.sound.js (chunk-vendors.js:7513)
    at __webpack_require__ (app.js:785)
```

**Comment by francoispeyret** [comment]
> This is not working for me
> I get this error:
> 
> ```
> Uncaught ReferenceError: p5 is not defined
>     at Object.eval (p5.sound.js?e617:3112)
>     at Object.eval (p5.sound.js?e617:3160)
>     at __webpack_require__ (p5.sound.js?e617:84)
>     at Object.eval (p5.sound.js?e617:2885)
>     at Object.eval (p5.sound.js?e617:2956)
>     at __webpack_require__ (p5.sound.js?e617:84)
>     at eval (p5.sound.js?e617:120)
>     at eval (p5.sound.js?e617:122)
>     at Object../node_modules/p5/lib/addons/p5.sound.js (chunk-vendors.js:7513)
>     at __webpack_require__ (app.js:785)
> ```

same here

**Comment by rjbultitude** [comment]
I have the same error also. Tried with Webpack and Parcel using p5 v1.0
@therewasaguy Should this be re-opened or a new one created?

**Comment by PickleNik** [comment]
npm i p5@0.9.0 fixes the problem temporarily. Created new issue for that here: https://github.com/processing/p5.js-sound/issues/453#issue-604885354
