### ISSUE TITLE
i can only open my index when it in the trash can

### ISSUE THREAD

**Issue by JiahuiWang0616** [processing/p5.js-sound#218]
yesterday every thing is alright, today i didn't do any change and  it suddenly can't works.

127.0.0.1 - - [27/Sep/2017 11:30:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Sep/2017 11:30:26] "GET /Desktop/ HTTP/1.1" 200 -
127.0.0.1 - - [27/Sep/2017 11:30:27] "GET /Desktop/p5/ HTTP/1.1" 200 -
127.0.0.1 - - [27/Sep/2017 11:30:28] code 404, message File not found
127.0.0.1 - - [27/Sep/2017 11:30:28] "GET /Desktop/p5/empty-example/path/to/p5.sound.js HTTP/1.1" 404 -

but when i put it in the trash can, it works, it can only works in trash can...
127.0.0.1 - - [27/Sep/2017 11:30:35] "GET /.Trash/ HTTP/1.1" 200 -
127.0.0.1 - - [27/Sep/2017 11:30:36] "GET /.Trash/p5%2011.06.30/ HTTP/1.1" 200 -
127.0.0.1 - - [27/Sep/2017 11:30:37] "GET /.Trash/p5%2011.06.30/empty-example/ HTTP/1.1" 200 -
127.0.0.1 - - [27/Sep/2017 11:30:37] code 404, message File not found
127.0.0.1 - - [27/Sep/2017 11:30:37] "GET /.Trash/p5%2011.06.30/empty-example/path/to/p5.sound.js HTTP/1.1" 404 -
127.0.0.1 - - [27/Sep/2017 11:30:37] "GET /.Trash/p5%2011.06.30/empty-example/sketch.js HTTP/1.1" 200 -

please help me

**Comment by meiamsome** [comment]
Can you run `ls -lah` in `/Desktop/p5/`? Thanks!

**Comment by JiahuiWang0616** [comment]
Thanks for your reply, i already fixed this problem.
