### ISSUE TITLE
missing types in yui docs

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js-sound#220]
here's some errors in the docs:

    p5.sound.js:4261, return has invalid type: Tone.Signal
    p5.sound.js:4330, return has invalid type: p5.SignalAdd
    p5.sound.js:4349, return has invalid type: Tone.Multiply
    p5.sound.js:4368, return has invalid type: p5.SignalScale
    p5.sound.js:7677, param "input" has invalid type: WebAudioNode
    p5.sound.js:7677, param "output" has invalid type: WebAudioNode
    p5.sound.js:7677, param "wet" has invalid type: WebAudioNode

**Comment by montoyamoraga** [comment]
because of the age of this issue, i am closing it for now ~
