### ISSUE TITLE
Is it possible to use my speaker (or headphone) audio as AudioIn?

### ISSUE THREAD

**Issue by donpinkus** [processing/p5.js-sound#221]
Basically, if I'm playing a song on Spotify, can I use that as audio input?

**Comment by montoyamoraga** [comment]
When I do that on a Macbook I use [Soundflower](https://github.com/RogueAmoeba/Soundflower-Original), but it's hacky, another option can be using the [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API)

**Comment by donpinkus** [comment]
So this is meant to be used by other people visiting a site, so Soundflower
would be too much setup unfortunately.

I didn’t see anything in the Web Audio API that let’s you use speaker
output as input - are you thinking of something specific?

**Comment by elizasj** [comment]
I think the only solution for that would be to use your mic as an input, catching whatever is playing over your speakers.

Otherwise maybe an answer can be found in the spotify api docs.

**Comment by montoyamoraga** [comment]
closing this issue because it is outside of the scope of the library ~
