### ISSUE TITLE
set a mp3 stream as input

### ISSUE THREAD

**Issue by linksilver** [processing/p5.js-sound#225]
How can i put a MP3 stream as input ?
cant find anything in the doc

**Comment by therewasaguy** [comment]
If the MP3 stream is going into an [HTML5  `<audio>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#Audio_streamsWeb_Audio_API) like this 


```html
<!-- HTML-->
<audio id="my-stream" src="http://stream.m3u" autoplay></audio>
```

you can grab the p5.sound audio context, and then use it to [createMediaElementSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource) which you can then connect to other p5.sound objects, or to the master output (equivalent to [audioCtx.destination](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/destination) )


```javascript
# grab p5.sound audio context
var audioCtx = getAudioContext();

# create a reference to the <audio> element
var myMediaElement = document.getElementById('my-stream');

# create a media element source node
var source = audioCtx.createMediaElementSource(myMediaElement);

# connect to p5 master output
source.connect(p5.soundOut)
```

**Comment by therewasaguy** [comment]
it would be great to have a simpler way to do this within the library, but I am closing this for now

**Comment by Weckatron** [comment]
I was wondering if you could elaborate on this a bit because regardless of where I put this code, it doesn't work at all. getAudioContext doesn't exist among other things. I'm trying to make a p5 image react to sound from a live media stream.

**Comment by eric-delacruz-prod** [comment]
Weckatron did you ever find manage to have p5 react to sound from a live media stream?

**Comment by Weckatron** [comment]
Sadly not, this solution didn't work at all, and they don't seem to be updating it :(

**Comment by is0ly** [comment]
Hello! Did you manage to convey live sound into p5?

**Comment by Weckatron** [comment]
@is0ly I did not :( but the issue ended up having to do with Chrome blocking the code without user input. It has been a little while, so I don't remember it perfectly.

**Comment by is0ly** [comment]
bad
