### ISSUE TITLE
Add function to extract MFCC from audio

### ISSUE THREAD

**Issue by sagarsetru** [processing/p5.js-sound#228]
https://en.wikipedia.org/wiki/Mel-frequency_cepstrum

This will be very useful for all sorts of sound and audio applications! Shouldn't be too hard given that the FFT function already exists

**Comment by therewasaguy** [comment]
This is a great idea @sagarsetru, and truly it would be very useful!

However, as it stands we're using the [Web Audio AnalyserNode](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode) to get FFT efficiently, and this only gives us real numbers. To extract MFCC we need complex numbers.

It is possible to compute from a [ScriptProcessorNode](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode) that gives us access to the audio buffer. That node is deprecated as we all patiently await the [Audio Worklet](https://www.chromestatus.com/feature/4588498229133312). But in the meantime we are using ScriptProcessors elsewhere in p5 sound, and there are examples of other JS libraries that use it to compute complex FFT and do MFCC like this nifty library, Meyda https://github.com/meyda/meyda

If anyone is interested in bringing more advanced audio features to p5.sound, or providing examples of p5 in combination with a library like Meyda, that'd be very welcome!

**Comment by Foldover** [comment]
@therewasaguy Are there plans to update to/support Audio Worklets now that they are somewhat available? I'd love to write me some wasm-processors :D

**Comment by therewasaguy** [comment]
@Foldover hoping to do this, but no concrete plan yet. I think we'd need a fallback to script processor node for some time.

**Comment by Foldover** [comment]
@therewasaguy Ah, of course. Do you target any specific set of ecmascript? I've only seen ES6 examples of AudioWorklet in action.

**Comment by therewasaguy** [comment]
@Foldover We aren't targeting ES6, but welcome it. We are using promises in the library, and I think `class` is a good way forward.

We'd probably need a polyfill for some time, but would love to see us lay some groundwork for audio worklet!

**Comment by Foldover** [comment]
@therewasaguy That's awesome! If one can help in any way, I would love to :D .

**Comment by montoyamoraga** [comment]
as of 2023, this is beyond the scope of the library, so for now we are closing it ~
