### ISSUE TITLE
loadSound is not a function with Angular4

### ISSUE THREAD

**Issue by OrionStark** [processing/p5.js-sound#229]
Hello, I have some problems when I try to use p5js with Angular4. 
The Error said my loadSound is not a function. This is my code looks like: 
`import { Component, OnInit, AfterViewInit } from '@angular/core';
import * as p5 from 'p5';

@Component({
  selector: 'app-music',
  templateUrl: './music.component.html',
  styleUrls: ['./music.component.css']
})
export class MusicComponent implements OnInit {

  constructor() { }

  ngOnInit() {
    var myMusic = function (props) {
      var music;
      var fft;
      var canvas;
      props.preload = function () {
        music = props.loadSound("../../music/01-royal_blood-how_did_we_get_so_dark.mp3");
      };
      props.setup = function () {
        canvas = props.createCanvas(props.windowWidth-13, 500);
        music.play();
        fft = new p5.FFT();
        music.amp(1);
      };`

**Comment by therewasaguy** [comment]
hmm, you need to import p5.sound. Have you tried importing it like this?

```
import p5 from 'p5';
import 'p5/lib/addons/p5.sound';
```

via https://github.com/processing/p5.js-sound/issues/212#issuecomment-332238113 and https://github.com/processing/p5.js-sound/issues/137

**Comment by endurance21** [comment]
@therewasaguy this needs to closed i dont there is much left to answer
?. 
@OrionStark ?.

**Comment by OrionStark** [comment]
@endurance21 hey, sorry for not closing this issue. The problem has been fixed with @therewasaguy solution. Thanks for you all.
