### ISSUE TITLE
various errors running sound reference examples test

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js-sound#246]
to repro:
- checkout p5.js sources
- npm run docs:dev
- http://localhost:9001/test/test-reference.html

you'll see
- missing assets (Damscray_DancingTiger.mp3 - 404)
- Cannot read property `inputChannels` of null
- the `dL` is not defined error which I submitted a PR for
- Cannot read property `disconnect` of undefined
- Cannot read property `stop` of null
- `monostyn.loadPreset` is not a function
- Cannot read property `currentRetry` of undefined

**Comment by montoyamoraga** [comment]
this issue is stale, too much has changed since then, so i am closing it for now ~
