### ISSUE TITLE
AUDIO SYNC HELP !!

### ISSUE THREAD

**Issue by nomiliveson** [processing/p5.js-sound#250]
VERY BASIC

**trying to play multiple audio files simultaneously, but they play back at different times 
- also it has a pharrell-like 4 count start before playing..**

code:

var playerRate = 1;

function preload() {

  song1 = loadSound('assets/melody1.mp3');
  song2 = loadSound('assets/melody2.mp3');
  song3 = loadSound('assets/melody3mp3');
  song4 = loadSound('assets/melody4.mp3');
  song5 = loadSound('assets/melody5.mp3');

}

function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
 
  song1.playMode('restart');
  song2.playMode('restart');
  song3.playMode('restart');
  song4.playMode('restart');
  song5.playMode('restart');

}

function draw() {

   if (key == '1') {

    song1.loop();
    song2.loop();
    song3.loop();
    song4.loop();
    song5.loop();

  }

}

Please Help

Thank U <3 X O

**Comment by datramt** [comment]
Hi nomiliveson,

For this scenario, you'll want to take everything out of the draw() loop (or delete the draw loop entirely) and put it in an event listener. Right now, the draw function is continuously re-triggering the loop method on each song at the frame refresh rate. Try making a keypressed() event listener by placing the following code at the very end:

function keyPressed() {
	if (key === '1') {
		song1.loop();
		song2.loop();
		song3.loop();
		song4.loop();
		song5.loop();
	}
}

**Comment by nomiliveson** [comment]
hey @datramt  - thank you

the audio files till play with a delay, however

-they are not syncronised

**Comment by tstefanich** [comment]
Hello @nomiliveson,

What browser are you using? (I am using Firefox 58.0.2, p5 v.0.6.0 and p5.sound v3.7.0)

To my ears, your files seem to be in sync, and they play pretty instantaneously when I click a key. I also let the patch play for 30 minutes to see if they would get out of sync over time but they seemed to be still aligned for me. 

@datramt attached are a sample of @nomiliveson files

[PLYR.zip](https://github.com/processing/p5.js-sound/files/1741502/PLYR.zip)

**Comment by therewasaguy** [comment]
@datramt had the right suggestion to interactions out of `draw` (the animation loop) and into event handlers like `keyPressed`

Closing for now but feel free to reopen if it's still an issue, @nomiliveson !

**Comment by therewasaguy** [comment]
closing for now, but feel free to reopen with browser info, @nomiliveson ...very cool sounds btw!

**Comment by EXPSTUDIOmo** [comment]
Hey I have the same Issue using Chrome 90.0.4430.93

In Firefox everything is perfectly in Sync but using Chrome there is a slight delay between each sound.

**Comment by joex92** [comment]
Hi, 
I've been testing, uploaded it here https://joex.apps.dj/PLYR
when the page have been playing for a long time the audio begins to sound glitchy, why is that? is it have to do with the buffer? how do I fix it?
