### ISSUE TITLE
Broken links on p5.Effect reference page

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#251]
_From @andrewesterhuizen on January 7, 2018 13:28_

Hello, I just noticed the links for p5.Distortion, p5.Compressor, p5.Delay, p5.Filter, p5.Reverb on the [https://p5js.org/reference/#/p5.Effect](https://p5js.org/reference/#/p5.Effect) reference page are broken. It seems like they all have /reference/ twice in their path.

_Copied from original issue: processing/p5.js-website#156_

**Comment by TanviKumar** [comment]
#252 made to fix broken links.

**Comment by montoyamoraga** [comment]
fixed ~
