### ISSUE TITLE
Tutorial for audio() api?

### ISSUE THREAD

**Issue by Extarys** [processing/p5.js-sound#253]
Is there a tutorial on how to make animations with the audio() api from HTML5?

I'm making a little node-webkit app and everything is already setup with the audio() api but I cannot find a way to use this as a source and make animations using p5.sound.

Thanks!

**Comment by therewasaguy** [comment]
Hi @Extarys I think you are looking for [createMediaElementSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource) which sends a regular HTML5 audio (or video) element into a Web Audio node, that can be connected to other web audio nodes (or p5 sound nodes if that's what you're working with)
