### ISSUE TITLE
MIDI in p5.js

### ISSUE THREAD

**Issue by JunShern** [processing/p5.js-sound#258]
Hi, 

I was wondering what is the p5.js stance on MIDI? MIDI is such a crucial part of music production and art, so it seems natural that p5.js should have some support for it. From what I can see, p5.js-sound has [some](https://p5js.org/reference/#/p5/freqToMidi) [functions](https://p5js.org/reference/#/p5/midiToFreq) to convert MIDI note numbers <-> pitch frequencies, but is not yet able to handle MIDI messages in any way - is that right?

As I understand it, the [Web MIDI API](https://www.w3.org/TR/webmidi/) works well but [apparently](https://caniuse.com/#feat=midi) is supported only on Chrome, which I'm guessing is the main reason that MIDI is not yet supported on p5.js. (There seem to be [workarounds](https://github.com/cwilso/WebMIDIAPIShim) for other browsers, but I have not explored this)

Even if we cannot handle MIDI messages, we could still have the feature to load SoundFonts and synthesize them in the browser, right? This would be great for users (like myself) who wish to produce music in p5.js without having to define my own oscillators, not to mention that synthesizing natural-sounding instrument voices using oscillators is impractical in most cases.

Inspiration (with links to many awesome demos): [MIDI.js](https://galactic.ink/midi-js/)

**Comment by therewasaguy** [comment]
Good idea to think about MIDI!

Web MIDI is exciting, but as you mentioned, MIDI itself isn't super accessible via the web—only in Chrome or with special plugins. It's a nice bonus if a user is able to hook up a MIDI keyboard to a project, or able to trigger MIDI messages in a DAW so that they can just focus on using p5 to generate the notes. It could be worth providing some examples for how to do that, but it limits our audience if we depend on that functionality.

MIDI can be a useful framework for thinking about music as numbers. So we use freqToMidi and midiToFreq to make it easier to work with pitch as numbers, without reinventing the wheel. Sometimes we already have decent numbers in Web Audio, which I think is a better reference—for example, there's not really a reason to think of velocity between 0 and 127, so we can normalize that range to 0-1 to match the Web Audio API gain node.

MIDI time representation was designed to be read more by machines than humans. For example, you can't have a note duration, but instead need to do that with velocity changes (note on/off) over time. So I think we'd need higher level abstractions around time that are more human-friendly. [Tone.js MIDI Convert](https://github.com/Tonejs/MidiConvert) is a cool example of translating MIDI scores into a JSON format that is a bit more human-readable. It integrates well with Tone.js structures for working with pitch / duration / velocity over time, which are really well thought out.

midi.js is inspiring, too! Porting soundfonts to the web is a cool idea. Would we add these soundfonts to the library or point to some separate source(s)? I don't know how many users we could expect to load soundfonts, let alone generate them, which I recall being a bit of a deep process with midi.js. If the goal is to make it quick for users to get decent sounds, maybe there are simpler ways to accomplish this, like the incorporation of presets into p5 effects and synths (which started last summer)

**Comment by b2renger** [comment]
about sound fonts,  I used this :  https://github.com/danigb/soundfont-player

example with p5js (press keyboard from 's' to 'l' : 
https://b2renger.github.io/Introduction_p5js/07_audio_01_soundfont/index.html

code : https://github.com/b2renger/Introduction_p5js/tree/master/07_audio_01_soundfont

**Comment by JunShern** [comment]
@b2renger that's very cool, and pretty much exactly what I had in mind! If we can support this kind of behaviour in p5.js, I would be a happy cookie! But before getting into how exactly to bring SoundFonts in, I think there's more groundwork we need to do.

@therewasaguy 

Fair enough, I agree that we shouldn't exclude some of our audience. In any case, we don't need Web MIDI to produce standalone music in the browser, which at least for me is the more important goal before we think about connecting hardware and native DAWs.

That said, I believe it is quite important to maintain MIDI-compatibility beyond the level of note-numbers (just so that users can do things like load MIDI files into their programs, save their compositions as MIDI files, also so we don't close off the possibility of eventual hardware/DAW integration. 

Since you brought up the point of representation, I would also like to push for a compact way to handle notes in p5.js, such as **a new p5.Note class** which captures information about pitch, velocity and timing in one package. This will be incredibly useful if we want to bring more advanced compositional capabilities to p5.js.

I completely agree that MIDI messages in general are not designed for humans, and p5.js definitely needs to be more human-centric! I like the Tone.js JSON representation you pointed at. I picked out this from their example, it seems like they use this representation for a single note:

```
// Tone.js JSON note representation
midi: Number,               // midi number, e.g. 60
time: Number,               // absolute time from song start, in seconds
note: String,               // note name, e.g. "C4"
velocity: Number,           // normalized 0-1 velocity
duration: Number,           // duration between noteOn and noteOff
```

which could be a great basis for a Note class in p5.js. This differs from how other notes are encoded in MIDI files, which uses

```
// MIDI message note representation
midi: Number,               // midi number, e.g. 60
time: Number,               // time delay from the previous note event in seconds
velocity: Number,           // normalized 0-1 velocity
```

and requires a second note with velocity = 0 (noteOff) to end the note, since there is no duration parameter. These are very different representations, and at first glance the Tone.js version seems far more intuitive. However, each has its pros and cons:

**Tone.js**
- [PRO] The duration parameter is very useful and much more intuitive than having a separate noteOff event.
- [CON] The duration of a note is not known in advance during a real-time scenario (when a player starts a note, for example in a browser keyboard application, we don't have information about how long he will hold it)
- [CON] The use of absolute time makes the notes less portable - it only works in the context of a global song, so for instance we cannot just grab a random note from the middle of the song and play it "right now". 

**MIDI**
- [PRO] The use of relative time delay from previous note is more local, and we can handle notes without worrying about where it fits into our whole song. This allows for use cases like storing an array of notes, and sampling from the array randomly to make a song - which is a crucial way that I expect people will want to interact with notes.
- [CON] Relative time delay FROM the previous note is far less intuitive than relative time delay TO the next note. (The reason MIDI does this is for the same reason about not knowing how long the delay is in a real-time scenario)
- [CON] We have to remember to produce the corresponding noteOff event as well. 

I will also _note_ that [our own synth classes](https://p5js.org/reference/#/p5.MonoSynth) also use the same absolute time representation, but while this is fine for note playback, I feel that individual note storage needs to be local. I would also point out that despite an absolute time representation, even the [current documentation](https://p5js.org/reference/#/p5.MonoSynth) shows the user thinking in terms of time delays rather than absolute times:

```
monosynth.play(45,1,x=0,1);
monosynth.play(49,1,x+=1,0.25);
```

Unfortunately, the time parameter in general is not very intuitive to think about, but it is crucial to have it defined separately from duration, otherwise we cannot have polyphony. Based on this, I can see one possible option which has the best of both worlds - locality, intuitiveness and ease-of-use.

```
// Proposed note representation
midi: Number,               // midi number, e.g. 60
time: Number,               // relative time delay to the next note event
note: String,               // note name, e.g. "C4"
velocity: Number,           // normalized 0-1 velocity
duration: Number,           // duration between noteOn and noteOff
```

To me, this seems like the perfect scenario for a generative application, but it does not lend well to the idea of real-time performance recording (but I think there might be ways to work around this, such as filling the time and duration parameters with a special flag to indicate that the values are not known - in which case the synth should hold the note indefinitely?).

**Comment by therewasaguy** [comment]
Great analysis here.

I think a p5.note class that draws inspiration from MIDI (where it is helpful) is an interesting idea. Though I also worry about adding too many new classes to the API, which can make it feel intimidating.

Time is definitely something to try to figure out, and something that I hope we can tackle as part of algorithmic examples. So I'm glad you brought it up!

Currently time is represented as "timeFromNow" across p5.sound. This is different from MIDI as you've pointed out which uses relative time delay to the next note event. It's also slightly different from Web Audio that uses AudioContext Time. In hindsight it would've been nice to be consistent with Web Audio time, similar to the way `millis` can be useful for visualization in p5.

The `p5.soundLoop` was meant to allow for experimentation with relative time delay. We do this by changing the `interval` until the next iteration of the sound loop. [Here's an example](http://alpha.editor.p5js.org/talkscheap/sketches/SydY4pKKM).

I think it's important to be consistent with our representation of time within the library. So I hesitate to introduce new ways to represent time in the p5 sound API, unless it's part of a major update (and breaking change) across the entire library.

**Comment by JunShern** [comment]
Thanks for the example, @therewasaguy ! This helps clarify the options we have. I think I'll focus on getting a simple algorithmic composition example working now, this ought to make clear what we have that works well, and where we might need new features to improve the programmer's experience. 

Quick question, you mentioned something about presets for synths - is there an example for this? I still would like to try to incorporate pre-rendered soundfonts like @b2renger did simply because it provides a wealth of sound options quickly and easily, but I'd be interested to know if there are easier ways to get instrument sounds using the existing synth classes.

**Comment by therewasaguy** [comment]
> you mentioned something about presets for synths - is there an example for this? 

@jvntf made great progress on this idea in this branch https://github.com/processing/p5.js-sound/commits/presets for example https://github.com/processing/p5.js-sound/commit/c4493b20a454219d07f5d5919a9903bb90e3977f#diff-559e243463d4dac174c5eee32f469a81R174

**Comment by JunShern** [comment]
Thanks guys for the discussion! I'm going to close this issue for now, I plan to carry on some of these ideas in more focused threads.

**Comment by eclewlow** [comment]
Native support would be cool.  Not a lot of steps to integrate with browser built-in midi.

Example:
https://gist.github.com/eclewlow/96d9cc8628157842d56962880bbefdd3

References:
https://www.keithmcmillen.com/blog/making-music-in-the-browser-web-midi-api/
https://www.midi.org/17-the-mma/99-web-midi

**Comment by eclewlow** [comment]
Sorry this might all already be implemented with `p5.PolySynth()`
