### ISSUE TITLE
Manually edited VS generated index.html

### ISSUE THREAD

**Issue by JunShern** [processing/p5.js-sound#263]
Hi! 

So I was just getting acquainted with our 'examples' folder, and inspecting the `generator.js` and resulting index.html. To confirm that it works as expected, I ran the command `node gh-page/generator.js` from the top-level directory and got a new `index.html` file generated. However, there were a few differences between my newly generated `index.html` file and the previous one:

1. The generated `index.html` has the p5.js logo link `src="http://p5js.org/img/p5js-beta.svg"` which seems to be a broken link, versus the link in the exisiting `index.html` which is `src="http://p5js.org/img/p5js-beta.svg`. 

2. The following examples did not exist in the previous index.html, but generator.js does generate them:
- `monosynth_basic` 
- `polyphonic_synth` (which has been "commented out because it is outdated")
- `sound_loop`

3. The following examples exist in both versions but not in the same order on the list:
- `graphical_eq`
- `Compressor`

4. A `testing_stuff` example is on the previous `index.html`, but does not have corresponding files in the examples folder and hence leads to a broken link.

I'm guessing that the above problems were caused by people manually editing the `index.html` file instead of using the `generator.js` script to generate it. Instead of manually editing `index.html`, people should use the '_' prefix in their folder names if they don't want the folder to be generated, and the new p5.js logo should be updated in `generator.js`.

@therewasaguy please confirm that my understanding is correct? If so, I will make a pull request that:
- Updates `generator.js` to "legally" reproduce the manual changes in `index.html`
- Adds some documentation on how to create examples on the [Contribute](https://github.com/processing/p5.js-sound/wiki/Contribute) document 
- Use the generator to add a DO NOT EDIT warning on `index.html` so that future users don't make the same mistake

**Comment by therewasaguy** [comment]
awesome work making sense of this, and improving documentation for the next person who encounters it, @JunShern!
