### ISSUE TITLE
async issue during p5.js reference test

### ISSUE THREAD

**Issue by Spongman** [processing/p5.js-sound#269]
if you run the p5.js reference tests in the browser (by running `npm run docs:dev` in the p5.js repo), aside from a bunch of 404-related issues, you'll see a pretty bad bug resulting from asynchronous operations completing after the p5 instance has been removed.

the timeline of the specific bug i'm seeing is this:
- the 'pause documentation' sketch runs
- the test framework instantiates a p5 instance
- the test calls `loadSound()`
- the test framework then calls `p5.remove()` to remove the instance
  - the SoundFile object is disposed, setting `this.panner = null`
- the `XMLHttpRequest` inside `p5.SoundFile.prototype.load` completes
  - it atempts to access `self.panner.inputChannels`. since `self.panner` is is now null, this results in an exception.

i think this is a wider issue with the p5 library itself - it's not resilient to having `remove()` called at inopportune times. but this specif SoundFile instance is causing these tests to fail.

**Comment by therewasaguy** [comment]
thanks for raising this issue.

Some of this should be resolved by your PR here, right? https://github.com/processing/p5.js-sound/pull/270

Can we come up with a more specific issue description if more can be fixed in p5.sound repo?

**Comment by montoyamoraga** [comment]
per the last comment, this issue was fixed by #270
