### ISSUE TITLE
canvasSaturation when playing multiple times

### ISSUE THREAD

**Issue by DDV2** [processing/p5.js-sound#273]
Hi. When playing a sound multiple times, lets say like 40 times in my case, (is a sound efect of shooting in my game, but in this simple animation it happens too) the page start to saturate, and the animation looks lagged. Can somebody try it ?

```
let x;
let vel;
let sound;
function preload(){
  sound = loadSound("disparosMagia.mp3");
}
function setup(){
  createCanvas(1000, 650);
  sound.playMode("restart");
  x = 100;
  vel = 1;
}

function draw(){
  background(200);
  ellipse(x, 300, 200, 200);
  x+= vel * 5;
  if(x > 900 || x < 100){
    vel *= -1;
  }

}
function keyPressed(){
  sound.play();
}

```

**Comment by GoToLoop** [comment]
https://Forum.Processing.org/two/discussion/27873/soundsaturation

**Comment by DDV2** [comment]
https://github.com/processing/p5.js-sound/issues/88
