### ISSUE TITLE
new chrome autoplay policy

### ISSUE THREAD

**Issue by datramt** [processing/p5.js-sound#274]
Apologies if this is already on the radar.
Chrome seems to have just implemented their new autoplay policy:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

This kind of renders most p5.sound sketches ever made semi-broken unless the AudioContext is resumed after a listener event. This includes most of the documentation examples as well.

The p5.sound fix that I'm thinking about adding to ALL of my sketches is simple: 

```
let ctx, ctxOn;

function setup() {
    ctx = getAudioContext();
    ctxOn = createButton('turn on Audio');
    ctxOn.mousePressed(() => {
  	ctx.resume().then(() => {
  	console.log('Audio Context is now ON');
        ctxOn.hide();
  	});
    });
```

I'm curious if there is discussion or ideas on how to make this more simpler for anybody using p5.sound with chrome(?). I'm thinking either a helper function to initialize every audio sketch with a button, or something even more under-the-hood. I'd be surprised if other browsers didn't follow chrome's lead on this.

**Comment by datramt** [comment]
(my bad) #249

**Comment by archaicvirus** [comment]
`function mousePressed()
{
	getAudioContext().resume()
}`

This fixed my guitar tuner app, using p5 oscillators.
