### ISSUE TITLE
<video> .play().time(nn) not working in Chrome 66.0.3359.139 on Macos 10.13.4

### ISSUE THREAD

**Issue by Pumpapa** [processing/p5.js-sound#276]
```
function setup() {
	var x=windowWidth, y=windowHeight

	createCanvas(x,y);
	
	var th = createVideo('TH.mp4');
	th.size(300,AUTO).position(400, 50);

	createButton('play').position(100, 25).mousePressed(() => th.play());
	createButton('pause').position(200, 25).mousePressed(() => th.pause());
	createButton('+60').position(300, 25).mousePressed(() => th.play().time(200));
}

function draw() {
}
```
In Chrome pressing +60 doesn't work, whereas in FF it does. In Chrome this restarts at 0.
Am I missing something?

I'm trying to create interactive videos, so seeking is quite relevant.

I've been debugging for hours, and I have the impression Chrome's P5-video behaviour is erratic but by now I'm unsure.

**Comment by therewasaguy** [comment]
Hi @Pumpapa, thanks for raising this issue.

`createVideo` is a method from p5.dom library which lives in the p5.js repo. Would you mind posting the issue over this way https://github.com/processing/p5.js/issues ?
