### ISSUE TITLE
Bug in SoundLoop.pause()

### ISSUE THREAD

**Issue by JunShern** [processing/p5.js-sound#286]
Hi, I found a bug in the `p5.SoundLoop.pause` method, that the method doesn't actually pause the loop as it is supposed to. The issue can be seen in the following example, where the play/pause button doesn't actually stop the audio from sounding at all:

```javascript
var loop;

function setup() {
  noCanvas();
  synth = new p5.PolySynth();
  loop = new p5.SoundLoop(soundLoop);

  button = createButton('Play/Pause');
  button.mousePressed(togglePlayPause);
}

function soundLoop(cycleStartTime) {
  synth.play('C4', 0.3, cycleStartTime, 0.5);
}

function togglePlayPause() {
  if (loop.isPlaying) {
    loop.pause();
    console.log("Loop playing? " + str(loop.isPlaying));
  } else {
    loop.start();
    console.log("Loop playing? " + str(loop.isPlaying));
  }
}
```

I believe I've identified the problem already, I'll try the fix and make a pull request.

**Comment by therewasaguy** [comment]
thanks for the issue + fix in https://github.com/processing/p5.js-sound/pull/287,  @JunShern !
