### ISSUE TITLE
New SoundfontSynth class for p5-sound?

### ISSUE THREAD

**Issue by JunShern** [processing/p5.js-sound#289]
Hi all! 

So I first touched upon the idea of using soundfonts for sound synthesis in #258 . I decided to start this new thread since this is not really about MIDI but just about soundfonts specifically. 

I've made some progress with the idea of using soundfonts as an alternative to our current synth voices, which you can try out in my `keyboard_voices` example [here](https://github.com/JunShern/p5.js-sound/tree/keyboard_voices_example/examples/keyboard_voices). The thing that I like about soundfonts is that they offer users a quick and easy way to get great-sounding instruments into their projects, without having to design their own voices (which of course is a great option to have, but not always the priority). 

I've built my example on top of @danigb 's [soundfont-player](https://github.com/danigb/soundfont-player) library, and came up with the following which provides a starting point to replicate the API of the PolySynth class for soundfonts: 

```javascript
SoundfontSynth = function(soundfont = 'acoustic_grand_piano') {
  this.audioContext = getAudioContext();
  this.inst = Soundfont.instrument(this.audioContext, soundfont);
  this.notes = {};
};

SoundfontSynth.prototype.play = function(note, velocity, secondsFromNow, duration) {
  this.inst.then(voice => {
    this.latest_note = voice
      .play(note, this.audioContext.currentTime + secondsFromNow, { 
        gain: velocity, 
        duration: duration
      });
  });
}

SoundfontSynth.prototype.noteAttack = function(note, velocity, secondsFromNow) {
  this.inst.then(voice => {
    this.notes[note] = voice
      .play(note, this.audioContext.currentTime + secondsFromNow, { 
        gain: velocity,
        loop: true // Need to set loopStart and loopEnd for smoother looping
      });
  });
}

SoundfontSynth.prototype.noteRelease = function(note, secondsFromNow) {
  this.notes[note].stop(this.audioContext.currentTime);
}
```

And this works pretty well except for one main difference I can see, which is that these soundfonts cannot sustain indefinitely - the duration of the note is limited to the length of the sample recording. This is not a problem for MIDI soundfonts in general because typically soundfonts are annotated with start and end points at which we can loop the audio sample for indefinite sustain. But although the [soundfont-player](https://github.com/danigb/soundfont-player) library does support looping (as well as defining loopStart and loopEnd points), these soundfonts themselves, pre-rendered by @gleitz for [midi-js-soundfonts](https://github.com/gleitz/midi-js-soundfonts), apparently do not come with that loop-start/end metadata (relevant [issue here](https://github.com/danigb/soundfont-player/issues/7)).

That said, that might be an issue we can tackle in the longer term, but as it is I do feel like even the simple duration-limited soundfont synth could be useful as is - I've been happily using it myself for the past couple of days. 

If anyone has any input on this, I would be happy to hear it! Also roping in @therewasaguy for thoughts.

**Comment by grant667** [comment]
I have been messing with making my own soundfonts for p5js but now leaning towards audiosprite where you basically stack all the sounds into 1 file and have it play silence as apposed to stopping it ever to keep the buffer. Then you simply use a Json file with the needed times and info.

**Comment by montoyamoraga** [comment]
since this issue hasn't received more comments since 2018,
and since we are on the process of refactoring the p5.sound.js library,
in favor of trimming it down with less features, i am closing this issue for now ~
