### ISSUE TITLE
addCue() does not return a number/Id. It returns NaN

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#306]
_From @wktdev on June 18, 2018 5:24_

I don't know if I am misreading the documentation or if this is an error. addCue does not return a number or "ID".  It returns NaN. 

https://p5js.org/reference/#/p5.SoundFile/addCue

Documentation quote:

> Returns
> Number: id ID of this cue, useful for removeCue(id)

**Example**

```
  mySound.play();
  let id = mySound.addCue(3, console.log,"we are the world");
  console.log(id)  //  NaN
```
  
### How does removeCue(id) work?
Ultimatley I am trying to understand how to use the removeCue(id) function and the documentation does not give a clear cut example. 

Can someone please show me and clear this up ? The documentation is very poor.

_Copied from original issue: processing/p5.js#3030_

**Comment by lmccart** [comment]
_From @EsdrasXavier on June 20, 2018 14:49_

Hello, I tried do the same thing and I also get the same error, so I looked at the source code 'p5.sound.js' and searched where this method is called... On line 2098:
`  p5.SoundFile.prototype.addCue = function (time, callback, val) {
    var id = this._cueIDCounter++;
    var cue = new Cue(callback, time, id, val);
    this._cues.push(cue);
    // if (!this.elt.ontimeupdate) {
    //   this.elt.ontimeupdate = this._onTimeUpdate.bind(this);
    // }
    return id;
  };`

But this._cueIDCounter has not been set, maybe just in version: 2018-01-19 v0.3.7 ... So I added this code in line 815:
`this._cueIDCounter = 0;`

Look works fine now, maybe a bug or just forgot to declare. Also I tried to use removeCue, which has a bug too on line 2119 the property is wrong, you need change this:
`this.cues.splice(i, 1);`
to
`this._cues.splice(i, 1);`
When you call the function mySound.removeCue(id), you will be able to delete the callback based on id passed by param returned by mySound.addCue().
Look this example:
`  

      function setup() {
        textSize(32);

        background(0);
        noStroke();
        fill(255);
        textAlign(CENTER);
        let mySound = loadSound('/teste_linhas/sound.mp3');
        mySound.play();
        let id = mySound.addCue(0.50, changeText, "a       a" );
        console.log(id);
        mySound.removeCue(id);
        id = mySound.addCue(1.0, changeText , " b     b" );
        console.log(id);
        id = mySound.addCue(3.0, changeText , "  c c" );
        console.log(id);
      }
      function changeText(val) {
        text(val, width/2, height/2);
      }
`

You probably not will be able to see the "a      a" string on canvas

**Comment by lmccart** [comment]
_From @limzykenneth on June 24, 2018 6:3_

Hi, can this issue be moved to the [p5.sound repo](https://github.com/processing/p5.js-sound)? As the source code for sound are hosted separately there. Thanks!

**Comment by therewasaguy** [comment]
fixed with https://github.com/processing/p5.js-sound/pull/298
