### ISSUE TITLE
granular sampler

### ISSUE THREAD

**Issue by b2renger** [processing/p5.js-sound#31]
Hello Everyone,

I tried to experiment a bit with granular sampling in p5.js-sound.

It turns out the the SoundFile class gets pretty much the job, all we need is a nice enveloppe. I have two drafts of code, one straigth ahead, and one with a class 

Here's a first draft of code 

```javascript

var source; // a sound
var src_length;

var grain_length =.5; // duration of grain

var peaks; // array for graphic representation


function preload(){
	source = loadSound('poldini.mp3'); // preload a sound
}

function setup() {
  createCanvas(windowWidth, windowHeight);
 
  peaks = source.getPeaks(windowWidth); // get the peak array

  src_length = source.duration(); // get duration of the sound
  console.log(src_length);
}

function draw() {
	background(180);

	// draw the waveform
	translate(0,height/2);
	noFill();
	stroke(0);
	for (var i = 0 ; i < peaks.length ; i++){
		var x = map(i,0,peaks.length,0,windowWidth);
		var y = map(peaks[i],0,1,0,windowHeight);
		line(x,0,x,y);
		line(x,0,x,-y);
	}

	// draw the playhead
	fill(255,255,180,150);
	noStroke();
	rect(mouseX,-height/2,map(grain_length,0,src_length,0,width),height);

	if (mouseIsPressed){
		if (frameCount%2 == 0){ // trying to be soft here

			var start_play = map(mouseX,0,width,0, src_length-grain_length); // map mouseX to playhead position
			var pitch = map(mouseY,0,height,0.5,1.5); // map mouseY to the set playing rate 

			playGrain(start_play, pitch,0.1,start_play,grain_length);	// play a grain !
		}
	}
}


function playGrain(start,rate,amp,cueStart,grLength){
	var grainDur = grLength;

	var att = grainDur*2/5;
	var dec = grainDur*1/5;
	var sus = 0.5;
	var rel = grainDur*2/5;

	var env = new p5.Env(att,dec,sus,rel);
	source.amp(env);

	source.rate(rate);
	source.jump(start,start+grLength);
	
	source.play();
	env.play(source);
	
}
```

and the second one with a GranularVoice class, and an array of voices 

```javascript

var source; // sound file
var src_length; // hold its duration

var peaks; // an array of peaks for the visual

var voices = []; // an array of voices
var num_voices = 50; 
var poly_counter = 0; // keep track of the last active voice
var grainDur = 0.5;

function preload(){
	source = loadSound('poldini.mp3'); // preload the sound
}

function setup() {
  createCanvas(windowWidth, windowHeight);
 // frameRate(25);

  src_length = source.duration(); // store the sound duration
  peaks = source.getPeaks(windowWidth); // get an array of peaks

  // build an array of granular voices 
  for (var i = 0 ; i < num_voices; i++){
	var voice = new GranularVoice(grainDur); // duration half a second per voice
	voices.push(voice); 
  }
  console.log(src_length);
  console.log(peaks.length);
}

function draw() {
	background(180);

	translate(0,height/2);
	noFill();
	stroke(0);
	
	// draw peaks
	for (var i = 0 ; i < peaks.length ; i++){
		var x = map(i,0,peaks.length,0,windowWidth);
		var y = map(peaks[i],0,1,0,windowHeight);
		line(x,0,x,y);
		line(x,0,x,-y);
	}

	// draw playhead
	fill(255,255,180,150);
	noStroke();
	rect(mouseX,-height/2,map(grainDur,0,src_length,0,width),height);

	if (mouseIsPressed){
		if (frameCount%2 == 0){ // trying to be soft here

		var start_play = map(mouseX,0,width,0, src_length-grainDur	); // map mouseX to position in the source
		var pitch = map(mouseY,0,height,0.5,1.5); // map mouseY to the rate the sound will be played

		// which voice to play
		poly_counter += 1;
		poly_counter = poly_counter%num_voices;
		// play it
		voices[poly_counter].playGrain(start_play, pitch,0.1,start_play,grainDur);	
	}
	}
}

function mouseIsPressed(){
	
}

function GranularVoice(grLength){

	this.sound = source;
	this.sound.playMode('restart');

	this.grainDur = grLength;

	// an enveloppe
	this.attack = this.grainDur*2/5;
	this.decay = this.grainDur*1/5;
	this.sustain = 0.5;
	this.release = this.grainDur*2/5;

	this.env = new p5.Env(this.attack,this.decay,this.sustain,this.release);

	// apply the enveloppe
	this.sound.amp(this.env);
}

GranularVoice.prototype.playGrain = function(start,rate,amp,cueStart,grLength){
	this.sound.rate(rate);
	this.sound.jump(start, start+grLength);
	this.sound.play();

	this.env.play(this.sound); // play the enveloppe
}
```

Both examples click a bit, I tried limiting the frameRate, I tried fiddling with the enveloppe parameters, but I still don't get a click-free result ... Any thoughts ?

**Comment by b2renger** [comment]
made a few modifications. 
1- I didn't read the doc rigth, I can use directly the play() with arguments ... instead of using .rate() etc.
2- Drawing is now done in the setup off-screen and then displayed as an image.
3- got rid of mouseIsPressed condition and the frameCount one : it seemed to cause clicks when .playGrain() was not called.
4- added methods to change grainDuration

It's better :) getting closer ...

```javascript
// mouseX = playback position
// mouseY = playback rate
// up arrow  increase grain duration
// down arrow decrease grain duration

var source; // sound file

var src_length; // hold its duration

var peaks; // an array of peaks for the visual
var pg;

var voices = []; // an array of voices
var num_voices = 40; 
var poly_counter = 0; // keep track of the last active voice
var grainDur = 1;

function preload(){
	source = loadSound('poldini.mp3'); // preload the sound
}

function setup() {
  createCanvas(windowWidth, windowHeight);
  frameRate(20);

  src_length = source.duration(); // store the sound duration
  peaks = source.getPeaks(windowWidth); // get an array of peaks

  // draw the waveform to an off-screen graphic
  pg = createGraphics(windowWidth,windowHeight);
  pg.background(180);
  pg.translate(0,height/2);
  pg.noFill();
  pg.stroke(0);
  for (var i = 0 ; i < peaks.length ; i++){
		var x = map(i,0,peaks.length,0,windowWidth);
		var y = map(peaks[i],0,1,0,windowHeight);
		  pg.line(x,0,x,y);
		  pg.line(x,0,x,-y);
	}
	console.log("nb of peaks : "+peaks.length);

  // build an array of granular voices 
 for (var i = 0 ; i < num_voices; i++){
	var voice = new GranularVoice(source,grainDur); // duration half a second per voice
	voices.push(voice); 
	
  }
  console.log("source duration : " +src_length);
  console.log("num voices : "+voices.length);
  
}

function draw() {
	background(180);

	var start_play = map(mouseX,0,width,0, src_length	); // map mouseX to position in the source
	var pitch = map(mouseY,0,height,0.5,1.5); // map mouseY to the rate the sound will be played
	// which voice to play
	poly_counter += 1;
	poly_counter = poly_counter%num_voices;
	// play it
	voices[poly_counter].playGrain(pitch,start_play,grainDur);

	image(pg,0,0); // display our waveform representation
	// draw playhead
	fill(255,255,180,150);
	noStroke();
	rect(mouseX,0,map(grainDur,0,src_length,0,width),height);

	fill(0);
	text('Grain Duration : ' + grainDur , 5,25);
}

function keyPressed(){
	if (keyCode === DOWN_ARROW){
		grainDur -=0.1;
	}
	else if (keyCode === UP_ARROW){
		grainDur += 0.1;
	}
	grainDur = constrain(grainDur,0.2,5);
}

function GranularVoice(src,grLength){

	this.sound = src;
	this.sound.playMode('sustain');

	this.amp = 0.05;

	this.grainDur = grLength;
	
	this.attack = this.grainDur*1/5;
	this.decay = this.grainDur*1/5;
	this.sustain = this.grainDur*2/5;
	this.release = this.grainDur*1/5;

	this.env = new p5.Env(this.attack,this.decay,this.sustain,this.release);

	// apply the enveloppe
	this.sound.amp(this.env);
	
}

GranularVoice.prototype.playGrain = function(rate,start,grLength){
	this.sound.amp(this.env);
	this.sound.play(0,rate,this.amp,start,grLength); 
	this.env.play(this.sound); // play the enveloppe	
}

GranularVoice.prototype.setGrainDur = function(newGrainDur){
	this.grainDur = newGrainDur;
	this.setAdsr(newGrainDur);
}

GranularVoice.prototype.setAdsr= function(newGrainDur){
	this.attack = newGrainDur*1/5;
	this.decay = newGrainDur*1/5;
	this.sustain = newGrainDur*2/5;
	this.release = newGrainDur*1/5;

	this.env = new p5.Env(this.attack,this.decay,this.sustain,this.release);
	this.sound.amp(this.env);
}
```

**Comment by therewasaguy** [comment]
@b2renger thank you for sharing your progress on this! It's very fun to play.

Would you like to submit a pull request adding this to the [examples](https://github.com/processing/p5.js-sound/tree/master/examples) folder? Feel free to use any of the audio files from the [_files](https://github.com/processing/p5.js-sound/tree/master/examples/_files) folder, it sounds great with "Dancing Tiger".

To develop this further, I'd play with [p5.Env](https://github.com/processing/p5.js-sound/blob/master/src/env.js). The clicks might be related to [this issue](https://github.com/processing/p5.js-sound/issues/22). Also, right now p5.Env only does [linearRampToValueAtTime](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/linearRampToValueAtTime), and this is a place where the option to change the shape of the envelope with exponentialRampToValueAtTime might really change the sound.

You've made a great use of the SoundFile.playMode('sustain') for multiple voices from the same buffer. But also raised an issue: 'Sustain' mode creates a new AudioBufferSourceNode every time .play() is called, while allowing any existing nodes to continue playing. Active SourceNodes are stored inside of the SoundFile's ``.sources``attribute. In your example, calling ```source.sources``` from the console, you can see that within just a few seconds, the sources array gets quite large. To optimize this we need to make sure that each AudioBufferSourceNode is scheduled to stop after its envelope goes back to zero, so that it can be garbage collected to avoid memory leaks. 

Another idea to explore - right now, you're triggering .play() within the draw loop, at 20 frames per second. This could be handled much faster and with more precision if it is scheduled on AudioContext time.

I hope we can dive into some of these issues, and develop this further into a GranularSynth class that could become part of the library. But even just the example you've made so far, with the ability to scrub through sound, I think will inspire some great projects!

**Comment by b2renger** [comment]
ok added to the examples !

for the audio files, could we add a small piece of classical music ? It generally sounds amazing with strings or polyphonic voices. Typically I use this kind of stuff with long classical samples, and grains up to 1.5 second to get rich textures. (I developped this with this tune : https://www.youtube.com/watch?v=4itAZd6Fr_0)

In the end it might be a good idea to have a GranularSynth class inheriting from a GranularVoice to hide all the polyphonic stuff.

You make a lot of good points, as for the p5.Env maybe we could imagine having a isPlaying() method ? (like the one in p5.SoundFile) and I actually didn't event try to do this.source.isPlaying(), I'll try and see if I can garbage collect manually at first.

Considering the rate of triggerring of play() I tried first to use small test to reduce the number of calls to play, and it didn't avoid the clicks.

```javascript
if(frameCount%5 == 0){
// trigger play...
}
```

Generally speaking juggling with the frameRate and the audioRate can be tricky, it's definitely interesting to try to work in that direction, to be able to schedule any kind of incomming data on audio context time.

**Comment by therewasaguy** [comment]
Sure, we can add a small classical sample to the _files. I just want to keep these to Creative Commons and Public Domain recordings, and to keep the total filesize small. [Here](http://freemusicarchive.org/music/Maude_Powell/Antique_Phonograph_Music_Program_08252009/Poupee_Valsante_Waltzing_Doll) is a public domain version of the tune you linked, though it has some intense victrola hiss, that actually sounds kind of cool. [Here's something](http://freemusicarchive.org/music/Soni_Ventorum/Franz_Danzi_Wind_Quintet_Opus_67/08_-_Danzi-_Wind_Quintet_Op_67_No_3_In_E-Flat_Major_4_Allegretto) that is CC-BY-SA and I think gets the timbre across. Definitely open to your suggestions for what to add, [musopen](https://musopen.org) is a great resource for PD classical music.

I just pushed a [change to p5.SoundFile](https://github.com/processing/p5.js-sound/commit/392e0d0b52527f99d736c8d2234f523e9b5abc97#diff-635fd3ddb6f066be99025f1994db3e30R297) that adds an ``onended`` event to every [AudioBufferSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode), to make sure each node is deleted from the sources array after it's done playing. Not sure if this is helping much, but now if you console log ``source.sources.length`` while running your example, you'll see how many grains are actually playing at that moment.

I like the idea of adding .isPlaying() to p5.Env. I had already been thinking it might be useful to set an envelope to loop. These could both be implemented similar to the p5.SoundFile methods.

I haven't been able to get rid of the clicks in your example, but here are two things to try:
- [p5.Env](http://p5js.org/reference/#/p5.Env) accepts ``time, value`` pairs, and if there are less than four pairs (ADSR), any values that are not provided will default to zero. So I was playing with [this line](https://github.com/processing/p5.js-sound/commit/b1d4cd5128913b6644770e4b219af34fcda8b54c#diff-ed618091ab231cb2e10a47a3a75d4f62R111). 
- Change the playGrain method so that the envelope only impacts the gain of the most recently created AudioBufferSourceNode.
```
GranularVoice.prototype.playGrain = function(rate,start,grLength){
    this.sound.play(0,rate,this.amp,start,grLength); 
    this.sound.sources[this.sound.sources.length-1].connect(this.env.output);
    this.env.play(); // play the envelope    
}
```

**Comment by b2renger** [comment]
I got it !

I actually moved from using enveloppe to build my own window and it seems to be ok now. But this means there is definitely an issue with the Env class.

In general when doing granular synthesis we use a trapezoidal window so that's what I went for. The method playGrain now looks like this : 

```javascript
GranularVoice.prototype.playGrain = function(rate,start,grLength){

  var now = getAudioContext().currentTime;

  this.attack = grLength*1/5;
  this.release = grLength*1/5;

  this.grainDur = grLength - (this.attack + this.release);
  
  this.sound.play(0,rate,this.amp,start,grLength); 
   
  this.sound.source.gain.gain.setValueAtTime(0.0, now);
  this.sound.source.gain.gain.linearRampToValueAtTime(this.amp,now + this.attack);
  this.sound.source.gain.gain.linearRampToValueAtTime(this.amp, now + this.attack + this.grainDur );
  this.sound.source.gain.gain.linearRampToValueAtTime(0,now + (this.attack + this.grainDur  + this.release) );
    
}
```

Glitch free :)

It's so simple it should be implemented  right in the play method of the SoundFile class. It would just involve adding three optionnal parameters (grainLength,attack, release), and just having to worry if attack+release>grainLength. The SoundFile class will be a granular sampler by default :)

Should I go for it ? 

the example will also be greatly simplified ! as we would just call the play method !

I'll look for the best extract to get nice sonic possibilities out of the example :) The wind example you linked is nice but with the attacks and release it gives you the impression of a small flutter effect which is very fun but that could be interpreted as a glitch . What size should I aim for ? having 45 sec of audio could be nice .

The auto garbage collecor is a really nice feature to have in this class :) and it works like a charm !

**Comment by b2renger** [comment]
ok here's where I am at now : 

```javascript
/ mouseX = playback position
// mouseY = playback rate
// up arrow  increase grain duration
// down arrow decrease grain duration

var source_file; // sound file

var src_length; // hold its duration

var peaks; // an array of peaks for the visual
var pg;

var voices = []; // an array of voices
var num_voices = 50; 

var grainDur = 1; // length of the grain

function preload(){
    source_file = loadSound('Blue_Danube_by_Strauss_extract.mp3'); // preload the sound
}

function setup() {
  createCanvas(700, 500);

  src_length = source_file.duration(); // store the sound duration
  peaks = source_file.getPeaks(windowWidth); // get an array of peaks

  // draw the waveform to an off-screen graphic
  pg = createGraphics(windowWidth,windowHeight);
  pg.background(180);
  pg.translate(0,height/2);
  pg.noFill();
  pg.stroke(0);
  for (var i = 0 ; i < peaks.length ; i++){
        var x = map(i,0,peaks.length,0,windowWidth);
        var y = map(peaks[i],0,1,0,windowHeight);
          pg.line(x,0,x,y);
          pg.line(x,0,x,-y);
    }

   // build an array of granular voices 
  for (var i = 0 ; i < num_voices; i++){
     var voice = new GranularVoice(source_file,grainDur); // duration half a second per voice
     voices.push(voice); 

   }
}

function draw() {
    background(180);

    if (mouseIsPressed && frameCount%2 == 0){
      var start_play = map(mouseX,0,width,0,src_length); // map mouseX to position in the source
      var pitch = map(mouseY,0,height,0.5,1.5); // map mouseY to the rate the sound will be played
      // which voice to play
      poly_counter += 1;
      poly_counter = poly_counter%num_voices;
      //play it
     voices[poly_counter].playGrain(start_play,grainDur,pitch);
    }
     
    image(pg,0,0); // display our waveform representation
    // draw playhead position 
    fill(255,255,180,150);
    noStroke();
    rect(mouseX,0,map(grainDur,0,src_length,0,width),height);

    fill(0);
    text('Grain Duration : ' + grainDur , 5,25);
}

function keyPressed(){
    if (keyCode === DOWN_ARROW){
        grainDur -=0.1;
    }
    else if (keyCode === UP_ARROW){
        grainDur += 0.1;
    }
    grainDur = constrain(grainDur,0.05,5);
}


function GranularVoice(src,grLength){
  // load a copy of our source in the main buffer
  this.sound = src;
  this.sound.playMode('sustain'); // we want polyphonic playing
   
  this.amp = 0.5;

  this.attack = grLength*1/10;
  this.release = grLength*1/10;

  this.grainDur = grLength - (this.attack + this.release);
}

GranularVoice.prototype.playGrain = function(start,grLength,rate){
  var now = getAudioContext().currentTime; // get the time

  // compute parameters for our enveloppe
  this.attack = grLength*1/10; 
  this.release = grLength*1/10;
  this.grainDur = grLength - (this.attack + this.release);
  
  // play the grain
  this.sound.play(0,rate,this.amp,start,grLength); 
   
   // acess the gain node to control it with ramps
  this.sound.source.gain.gain.setValueAtTime(0.0, now); // start at zero
  this.sound.source.gain.gain.linearRampToValueAtTime(this.amp,now + this.attack); // go to amp during attack
  this.sound.source.gain.gain.linearRampToValueAtTime(this.amp, now + this.attack + this.grainDur ); // stay during grain duration
  this.sound.source.gain.gain.linearRampToValueAtTime(0,now + (this.attack + this.grainDur  + this.release) ); // fo to zero for release  
}
```

it works and I'm considering options to wite a full class, adding methods to : 
- set amp, attack and release
- experimenting with the panner.
- add an option to reverse grains.

As for the sounds I found this : https://www.youtube.com/audiolibrary/music is that ok if I take something from there and cut it a bit ?

**Comment by b2renger** [comment]
I started working on integrating it to the library as a new class, it turns out that implementing this in the SoundFile class would imply to much modifications to he original code.

I will use the extract you provided, what I was hearing was actually a click. FIY I think we should allow for a delay time to clean the buffer after the sample is played. If you play with the rate and you have a grain of 1sec and a rate of 2 : your grain will actually be of 0.5sec, right ? if the enveloppe doesn't adjust to the rate you hear a click when the class disposes of the buffer.

To cover for that I added 1 sec to the endtime when calling play on the sound source :

```javascript
this.sound.play(0,rate,1,start,this.grainDur+1);
```
considering that my playrate is beewtween 0.2 and 1.5, 1 second is plenty and keeps a decent size of buffer array.

**Comment by b2renger** [comment]
I made a pull request to the latest example of granular sampler without clicks !

I think it would be nice to add this feature to the library and since the example relies on direct calls to the web audio api function it may be better to hide it from users.

I've tried building a class inside the lib but failed , I need to take a closer look at the doc :) but I've written a bit of documentation.

So it may be time to close this one.

**Comment by b2renger** [comment]
I'll re-open this, mainly to start discussion on how to integrate this in the lib. My point being that it probably shouldn't

Considering this : https://github.com/processing/p5.js-sound/issues/47

The granular voice shoud maybe built as a user synth, and use the AudioVoice and PolySynth implementation right ?

The main issue here is that it contains direct calls to the web audio api and those should be hidden for the user, so I'm a bit perplex on how to go on here ...

To put things in perspective the first versions of this code used p5.Env but there was a subtle click that I was only able to supress by building the enveloppe from scratch. This was referenced to this issue : https://github.com/processing/p5.js-sound/issues/22

I'll probably try a new implementation with p5.Env and the PolySynth implementation and see how it goes.
