### ISSUE TITLE
Question about TypeScript typings and current source/documentation

### ISSUE THREAD

**Issue by TeemuKoivisto** [processing/p5.js-sound#314]
Hello,

I started a project recently using TypeScript + React + p5 + p5.sound. However I soon noted that the TypeScript definitions weren't up-to-date with the current behavior of the library. Some of the errors were already addressed here https://github.com/p5-types/p5.ts/issues/3 but that leaves me with the conflicting typings of the p5.sound.

For example in the website example's https://p5js.org/examples/sound-record-save-audio.html a SoundFile is created without a parameter given to its constructor. This currently doesn't work with the typings as it requires 1-4 parameters. You can easily fix it locally by making the path optionable: `constructor(path?: string|any[],  ...` but I'm not sure what is the wanted behavior here.

Missing AudioIn properties were included in this PR https://github.com/processing/p5.js-sound/pull/310 so I guess it's fixed.

But I think there's a similar problem with SoundFile since it has a lot properties (buffer, bufferSourceNode, etc) that are not included in the SoundFile definition.

Is the amp method's typing fixed?
```
    amp(volume: number|object, rampTime?: number, timeFromNow?: number): void
```
should be:
```
    amp(volume: number|object, rampTime?: number, timeFromNow?: number): AudioParam
```

Possibly there's still some other problems that I have not uncovered yet since I've been only involved with a small set of p5.sound's API. One thing that bothered me was that to be able to save a file you have to call p5 instead of maybe SoundRecorder or SoundFile directly: `this.p5.saveSound(this.soundFile, 'sound-file.wav')`. I have a store that records/plays/saves audio and it would be nice to have it tidily encapsulated to only few properties of p5 API and not being dependent on the whole thing.

Teemu

**Comment by therewasaguy** [comment]
Thanks Teemu!

Feel free to fix any incorrect types in the documentation, or make specific issues for the ones that you find.

And good point about saveSound, that should be part of SoundRecorder or SoundFile as well as saving to a blob (https://github.com/processing/p5.js-sound/pull/312)

**Comment by therewasaguy** [comment]
@TeemuKoivisto https://github.com/processing/p5.js-sound/pull/315 would add a `save` method to p5.SoundFile, addressing part of this issue...

**Comment by montoyamoraga** [comment]
per the last comment, #315 solved some of this issues,
and as of 2023, we are writing this library in JS, not TS,
so this issue is beyond the scope of the library, so i am closing it for now ~
