### ISSUE TITLE
Microphone recording broken in Safari

### ISSUE THREAD

**Issue by dirkk0** [processing/p5.js-sound#324]
Hi,

  I hope it's just me, but I think sound recording is broken in Safari on both Mac OSX and iOS.
I am pretty sure it was working before. I don't have any errors on the console.

This example and others are not working for me:
https://p5js.org/examples/sound-mic-input.html

I am aware that Safari is the new Internet Explorer, but this is a major issue for me.

Thanks for looking into this.

Best, Dirk

**Comment by dirkk0** [comment]
ok, even more confusing:
this example does work on iOS ( I am still on 11.3):
https://p5js.org/reference/#/p5.AudioIn
but *not* on Safari 12.0.1, Mac OS High Sierra.

**Comment by ac3ro** [comment]
It is also broken for me in Mac Safari, iOS works fine. I'm building an application using P5js with the sound library and a couple of weeks ago it was the recorder was working. The issue occurs when trying to stop the recorder, with a "NotSupportedError: The operation is not supported"

Mac v10.13.6 - Safari Version 12.0.2 (13606.3.4.1.4)
iOS v12.1 and v12.1.1

Thanks!

**Comment by montoyamoraga** [comment]
because of the stalenes of this issue, i am closing it ~
