### ISSUE TITLE
DOMException error using p5.sound on Chrome 69

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-sound#328]
_From @petlil on September 20, 2018 5:1_

The most recent version of Chrome (69) seems to have compatibility issues with some p5.sound objects. Chrome 68 does not exhibit the error.

The error reads:
"DOMException: Failed to set the 'buffer' property on 'ConvolverNode': Cannot set buffer to non-null after it has been already been set to a non-null buffer"

#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Sound (p5.sound)

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.7.2
- Web browser and version: Chrome 69.0.3497.100 (Official Build)
- Operating System: Mac 10.13.1 (high sierra)
- Steps to reproduce this:
P5.sound example code for reverb encounters the error (several others also fail) on Chrome 69.
https://p5js.org/reference/#/p5.Reverb

Image of the error as it appears in the javascript developer console:
<img width="323" alt="screen shot 2018-09-20 at 5 00 14 pm" src="https://user-images.githubusercontent.com/43123543/45796833-acb01e00-bcf6-11e8-91d7-bb5a8bf409a1.png">

_Copied from original issue: processing/p5.js#3224_

**Comment by lmccart** [comment]
_From @dirkk0 on October 25, 2018 10:2_

Possibly related to this:
https://github.com/processing/p5.js/issues/3090

**Comment by dirkk0** [comment]
I ran into the same issue and mitigated the problem by not recreating the node but creating it once and connect and disconnect it respectively. But of course, this is only a workkaround.

        this.delay = new p5.Delay();
        this.delay.process(this.audio, .12, .7, 2300);
        this.delay.setType('pingPong'); // a stereo effect
        this.delay.disconnect()
and

        this.toggleDelay = function () {
            if (this.hasDelay) {
                this.delay.disconnect()
                this.hasDelay = false
            } else {
                this.delay.connect()
                this.hasDelay = true
            }
        }

**Comment by montoyamoraga** [comment]
closed because of Chrome 69 being outdated ~
