### ISSUE TITLE
SoundFile always saves as 44.1kHz instead of the sampling rate of the AudioContext

### ISSUE THREAD

**Issue by codygratner** [processing/p5.js-sound#341]
Lines 824-825 from p5.sound.js 0.3.10 (from the p5.js 0.7.3 release) has the sample rate hard coded at 44100 when saving a p5.SoundFile.

```
view.setUint32(24, 44100, true);
view.setUint32(28, 44100 * 4, true);
```

My audio interface is set to 48kHz and doesn't want to change. When using:

```
this.recorder = new p5.SoundRecorder();
this.soundFile = new p5.SoundFile();
this.recorder.record(this.soundFile);
this.recorder.stop();
save(this.soundFile, 'mySound.wav');
```

I end up with a wave file that is set to 44100, but correctly captures the 48000 sampling rate audio. I just open it in Wavosaur and change the sample rate to 48000 with no issues. But, those two lines can be changed to the following to fix that:

```
view.setUint32(24, p5sound.audiocontext.sampleRate, true);
view.setUint32(28, p5sound.audiocontext.sampleRate * 4, true);
```

I have no idea if that would break anything else? I saw issue #107 that didn't look related to this?

**Comment by therewasaguy** [comment]
Thanks and good call, @codygratner! Feel free to make a pull request with the fix
