### ISSUE TITLE
Phasing out of ScriptProcessorNode to the Audio Worklet API for p5-sound (GSoC 2019 project)

### ISSUE THREAD

**Issue by mebble** [processing/p5.js-sound#354]
Hi there. One of the projects for GSoC 2019 is the phasing out of ScriptProcessorNode (soon to be deprecated) to the Audio Worklet API for the p5-sound library. This is mentioned in the following places:
- [p5-sound TODO list](https://github.com/processing/p5.js-sound/blob/master/todo.md): Prepare to implement the AudioWorker, because ScriptProcessor will soon be depricated. We'll likely need a fallback during this transition.
- [GSoC Project List](https://github.com/processing/processing/wiki/Project-List#-utilize-the-audio-worklet-in-p5sound-library): Phase out use of the ScriptProcessorNode in favor of the Audio Worklet, with a fallback for unsupported browsers.

I found [this W3C resource](https://webaudio.github.io/web-audio-api/#AudioWorklet-concepts) regarding the concept and they've given a code example on instantiating an Audio Worklet. However, I'm not sure how I should incorporate it into this project.

Phasing to the Audio Worklet API is probaly a major overhaul to the p5-sound lib, so I'm guessing there's a discussion somewhere regarding this. I'd really appreciate some pointers on where to start. Do I need to directly contact the GSOC project's probable mentor, Jason Sigal to discuss the timeline and milestones for the GSOC project? Thank you.

**Comment by therewasaguy** [comment]
Hi @mebble! I'm sorry we did not get a chance to discuss over github. This project is happening this summer, please let me know if you'd like to be involved, or feel free to follow along and contribute here on github!

**Comment by mebble** [comment]
I'd love to be involved. Are there currently active issues regarding the audio worklet api?
