### ISSUE TITLE
Adding IRCAM's binaural FIR node

### ISSUE THREAD

**Issue by thely** [processing/p5.js-sound#363]
I'm working on a sonification project that uses a lot of spatialization. Previously I'd just been doing all the base Web Audio API coding myself, but a separate project helped me realize that p5 solved all my problems, save one.

I'm using [IRCAM's BinauralFIR node](https://github.com/Ircam-RnD/binauralFIR), which sounds a lot better than the base API's 3D panner. I tried adapting it to the p5 class structure, using `p5.panner3d` as my base, and it more or less looks the same. I put both the p5.binauralPanner adapter code (below) and the base file for the node itself (as `binaural.js`) in `src`, then added the necessary lines for it in the gruntfile. But when I run `grunt`, it seems like the files are getting ignored; I don't see the word "binaural" anywhere in the compiled `p5.sound.js` files, though the build reports "Done, without errors." I'm new to requireJS and compiling with grunt, so I'm sure I'm missing something, I'm just not sure what. Any ideas?

(I'm not using `time` anywhere because the node already has a `crossfadeDuration` property.)

`src/binauralPanner.js`
```
'use strict';

define(function (require) {
	var p5sound = require('master');
	var Effect = require('effect');
	var BinauralFIR = require('binaural');

	p5.BinauralPanner = function(hrtf, xfade) {
		Effect.call(this);

		this.panner = new BinauralFIR({
			audioContext: this.ac
		});
		this.panner.HRTFDataset = hrtf || 0;
		this.panner.setCrossfadeDuration(xfade);
		this.panner.connect(this.output);
		this.input.connect(this.panner);
	};

	p5.BinauralPanner.prototype = Object.create(Effect.prototype);

	p5.BinauralPanner.prototype.process = function(src) {
		src.connect(this.input);
	}

	p5.BinauralPanner.prototype.set = function(azi, ele, dist, xfade, time) {
	    this.azimuth(azi,time);
	    this.elevation(ele,time);
	    this.distance(dist,time);
	    this.crossfade(xfade,time);
	    return [this.panner.getPosition().azimuth,
              this.panner.getPosition().elevation,
              this.panner.getPosition().distance,
              this.panner.getCrossFadeDuration()];

	};

	p5.BinauralPanner.prototype.azimuth = function(azi, time) {
		var t = time || 0;
		if (typeof azi === 'number') {
			this.panner.setPosition(azi, this.panner.getPosition().elevation, this.panner.getPosition().distance);
		}
		return this.panner.getPosition().azimuth;
	};

	p5.BinauralPanner.prototype.elevation = function(ele, time) {
		var t = time || 0;
		if (typeof ele === 'number') {
			this.panner.setPosition(this.panner.getPosition().azimuth, ele, this.panner.getPosition().distance);
		}
		return this.panner.getPosition().elevation;
	};

	p5.BinauralPanner.prototype.distance = function(dist, time) {
		var t = time || 0;
		if (typeof dist === 'number') {
			this.panner.setPosition(this.panner.getPosition().azimuth, this.panner.getPosition().distance, dist);
		}
		return this.panner.getPosition().distance;
	};

	p5.BinauralPanner.prototype.crossfade = function(xfade, time) {
		var t = time || 0;
		if (typeof xfade === 'number') {
			this.panner.setCrossfadeDuration(xfade);
		}
		return this.panner.getCrossFadeDuration();
	};

	p5.BinauralPanner.prototype.hrtf = function(hrtf, time) {
		var t = time || 0;
		// if (typeof dist === 'number') {
		this.panner.HRTFDataset = hrtf;
		// }
		// return this.panner.getPosition().distance;
	};

	p5.BinauralPanner.dispose = function() {
		Effect.prototype.dispose.apply(this);
		if (this.panner) {
			this.panner.disconnect();
			delete this.panner;
		}
	};

	return p5.BinauralPanner;
});
```

`src/binaural.js`
```
'use strict';

define(function (require) {
	/* the contents of the BinauralFIR node, available here:
            https://github.com/Ircam-RnD/binauralFIR/blob/gh-pages/binaural-fir.min.js
        */
}
```

**Comment by thely** [comment]
Oof, figured it out! `binauralFIR` is on npm, so I was able to add it to the project and struggle my way through grunt/require from there.

Would this be something you all would be interested in seeing added to the codebase? It's not commented right now, but I could if it's not totally out of the question. Or would it be more prudent to release the resulting source code as an optional plugin for p5-sound?

**Comment by montoyamoraga** [comment]
hi @thely sorry about this stale issue, right now we are reducing the scope of the library, so we won't be implementing that for now, maybe the good folks at Tone.js would be interested? thanks!!
