### ISSUE TITLE
Uncaught Invalid State Error with implementing .start() after .pause()

### ISSUE THREAD

**Issue by justinpeake** [processing/p5.js-sound#37]
Not sure what "offset must be a non negative number" means

![screen shot 2015-04-23 at 10 22 13 am](https://cloud.githubusercontent.com/assets/8682347/7299099/8462b0fe-e999-11e4-94a2-7eb81be66cd1.png)

error thrown when I hit 's' key with the following code:

    function keyTyped() {
                    if (key === 'a') {

                       beat.pause();
                       bass.pause();
                       blip.pause();
                       texture.pause();

                      //paused = true;
                    } else if (key === 's') {

                       beat.play();
                       bass.play();
                       blip.play();
                       texture.play();
                  }
                }

**Comment by therewasaguy** [comment]
I will check this out asap. Must've brokenen with https://github.com/processing/p5.js-sound/issues/35, needs a unit test.

I've been meaning to implement a much better hack for tracking playback position, inspired by [Chinmay's Pendharkar's technique for Sonoport Sound Models](http://chinpen.net/talks/wac-paper/#/32).

Hopefully that'll be a temporary fix until improvements to the audiobuffersourcenode or until audio workers are here.

**Comment by justinpeake** [comment]
What's interesting is that it worked ONCE. It must've returned some positive value because I saw it work... once. Hahaha torturous.

- j

**Comment by therewasaguy** [comment]
Hey @justinpeake just pushed a fix, let me know how it goes!

https://raw.githubusercontent.com/processing/p5.js-sound/master/lib/p5.sound.js
