### ISSUE TITLE
No audio in Safari

### ISSUE THREAD

**Issue by sjnair** [processing/p5.js-sound#383]
Didn't see this previously reported.  I have a bunch of p5 sound projects that are currently working in Chrome (thanks to the userStartAudio workaround), but do not work in Safari (no audio).

Chrome: Version 76.0.3809.132 (Official Build) (64-bit)
Safari: Version 12.1.2 (14607.3.9)

Here are some of my projects which currently work in Chrome but not Safari:

http://www.seijinair.com/waves.html
http://www.seijinair.com/jazz.html
http://www.seijinair.com/musicbox.html

Is it related to this?  https://www.ibm.com/developerworks/library/wa-ioshtml5/

**Comment by yzxnwj** [comment]
I also found this problem.Have you solved it?

**Comment by joelyjoel** [comment]
I'm also having this problem. I added a one line polyfill that fixed some errors but not all:
```
window.navigator.getUserMedia = (...args) => window.navigator.mediaDevices.getUserMedia(...args);
```

**Comment by joelyjoel** [comment]
Its just a hypothesis, but could it be because p5 is using the promise-based form of the getUserMedia function?

```
    window.navigator.mediaDevices.getUserMedia( constraints )
      .then( function(stream) {
        self.stream = stream;
        self.enabled = true;
        // Wrap a MediaStreamSourceNode around the live input
        self.mediaStream = p5sound.audiocontext.createMediaStreamSource(stream);
        self.mediaStream.connect(self.output);
        // only send to the Amplitude reader, so we can see it but not hear it.
        self.amplitude.setInput(self.output);
        if (successCallback) successCallback();
      })
      .catch( function(err) {
        if (errorCallback) errorCallback(err);
        else console.error(err);
      });
  };
```
https://github.com/processing/p5.js-sound/blob/master/src/audioin.js

**Comment by joelyjoel** [comment]
This polyfill promises to fix it
https://github.com/mozdevs/mediaDevices-getUserMedia-polyfill

**Comment by joelyjoel** [comment]
What finally fixed it was updating to the newest version of p5sound

**Comment by sjnair** [comment]
Thanks for this update, didn't realize the issue had been addressed!
Updated my p5sound and sound is working now.

**Comment by montoyamoraga** [comment]
since the issue has addressed and it's working now, i will close this issue.
