### ISSUE TITLE
.pause() still behaving oddly

### ISSUE THREAD

**Issue by justinpeake** [processing/p5.js-sound#39]
So now even after #37 fixed, the 

- .pause() still doesn't seem to get called
- Console window shows " you pressed a" and "you pressed s"...
- .play() triggers file from beginning.

with this code:

     if (key === 'a') {

              console.log('you pressed a');

               beat.pause();
               bass.pause();
               blip.pause();
               texture.pause();

              //paused = true;
            } else if (key === 's') {

              console.log('you pressed s');

               beat.play();
               bass.play();
               blip.play();
               texture.play();
          }

**Comment by justinpeake** [comment]
and also, when .play() gets called, it's super hiccuppy to restart.

**Comment by therewasaguy** [comment]
works, but the new method of keeping SoundFile.currentTime should be revised once AudioWorkers are available for Web Audio API, and we can stop using the ScriptProcessorNode.
