### ISSUE TITLE
Chrome Issue(s) - Establishing Limiter on Master Output

### ISSUE THREAD

**Issue by cn-yn** [processing/p5.js-sound#41]
Hi, unlike several people on the Processing/p5 forum - I've had no problems using p5 sound with Chrome, except for this one line in the library which throws an error, but only in Chrome. It's marked with **** below. The error is 'Uncaught InvalidAccessError: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.'

This only happens in Chrome, but it causes it to fail to load the library. If I comment that line out everything runs smoothly (although I'm guess there's no limiter on the output then). 
```javascript
/**
 * Master contains AudioContext and the master sound output.
 */
  var Master = function () {
    var audiocontext = p5.prototype.getAudioContext();
    this.input = audiocontext.createGain();
    this.output = audiocontext.createGain();
    //put a hard limiter on the output
    this.limiter = audiocontext.createDynamicsCompressor();
    this.limiter.threshold.value = 0;
    this.limiter.ratio.value = 100;
    this.audiocontext = audiocontext;
    ****this.output.disconnect(this.audiocontext.destination);****
    // an array of input sources
    this.inputSources = [];
    // connect input to limiter
    this.input.connect(this.limiter);
    // connect limiter to output
    this.limiter.connect(this.output);
    // meter is just for measuring global Amplitude
    this.meter = audiocontext.createGain();
    this.output.connect(this.meter);
    // connect output to destination
    this.output.connect(this.audiocontext.destination);
    // an array of all sounds in the sketch
    this.soundArray = [];
    // an array of all musical parts in the sketch
    this.parts = [];
    // file extensions to search for
    this.extensions = [];
};
```

I'm a bit of a novice to all this stuff, hopefully I've reported this alright. There's one other weird thing in Chrome (hence the title issue(s) ), but I'm not sure if it should be reported separately. Briefly, it seems that using loop() on a sound file doesn't work, nor getting currentTime() (outputs 1 no matter what), so I can't create a workaround that checks the currentTime matching length and retriggers it. This is only in Chrome as well. Please let me know if you have any insight into either of these issues, or if I need to edit/report these differently/etc.

**Comment by therewasaguy** [comment]
Hi @cn-yn thanks for reporting these issues.

Both should be fixed with the latest version of p5.sound, which is unfortunately not on the CDN yet, but you can grab the code from this repo, or the p5.js repo.

https://raw.githubusercontent.com/processing/p5.js-sound/master/lib/p5.sound.js

**Comment by cn-yn** [comment]
Oh, awesome - works perfectly now - thanks, you are the man!

**Comment by dwehrmann** [comment]
This has helped me with a similar issue I was having using the files from the current download version on the p5js website.
