### ISSUE TITLE
How to manipulate Biquad Filters?

### ISSUE THREAD

**Issue by aadarshvelu** [processing/p5.js-sound#414]
So P5.js How to use the Biquad Filter using High pass and low pass? 
There is no well Documentation Available...

When I used to create a Biquad filter it throws an error.
`
  var biquadFilter = audio.createBiquadFilter();
`
visualCtrl.js:107 Uncaught TypeError: Cannot read property 'createBiquadFilter' of undefined

**Comment by endurance21** [comment]
hey ! @therewasaguy 
i would love to work on this issue , as i have already solved #411 , i can make this one too.
thanks !

**Comment by endurance21** [comment]
@aadarshvelu 
For using biquadFilters , 
we have it's aliase "P5.filter" , and for using it's features  like  highpass, lowPass , RangePass we already have documentations
see here  , 
https://p5js.org/reference/#/p5.Filter
![biquadFilter](https://user-images.githubusercontent.com/43696525/76809677-aaf2e800-6811-11ea-8ab8-c40a4af251b3.png)

try them out and let us know how it worked for you !
Thank you !

**Comment by endurance21** [comment]
@therewasaguy 
is there anything , i missed ?
i will love to hear it from you!

**Comment by aadarshvelu** [comment]
Yeah I got it thanks!

**Comment by endurance21** [comment]
@aadarshvelu  you are welcome !
