### ISSUE TITLE
TypeError: val.connect is not a function at p5.Oscillator.freq (p5.sound.js:1651)

### ISSUE THREAD

**Issue by JxM-92** [processing/p5.js-sound#416]
So, I'm working on a performance where I need to display on a web page colors and play sounds, but the instant that the Oscillator object is created it gives me a `vol.connect` issue... I don't understand, everything else in the code is fine, but that gives me an error when trying to change it...

**Comment by JxM-92** [comment]
I solve it, I, instead of changing the value of the oscillator outside draw() calling it directly, change the value of a variable calling the value inside draw()...

**Comment by JxM-92** [comment]
But I still don't understand the error... so if someone can explain to me why I had to do this to work:
`let osc, oscg;
function changeValue(val){
oscg = val;
}
function setup(){
osc = new p5.oscillator();
osc.setType = 'sine';
osc.amp(0);
osc.start(0);
}
draw(){
osc.amp(oscg);
}`
Instead of this:

`let osc, oscg;
function changeValue(val){
osc.amp(val);
}
function setup(){
osc = new p5.oscillator();
osc.setType = 'sine';
osc.amp(0);
osc.start(0);
}
draw(){
//any other thing happening here
}`

**Comment by endurance21** [comment]
@JxM-92 
hello!
i think you have there is typo error it not "p5.oscillator" it must be "p5.Oscillator"

and i have tested the osc.amp(Val) in the p5 web editor 
and i got nothing wrong!
it just worked in both ways !
but for the record and performance issue 
the first method is more appreciated !

**Comment by JxM-92** [comment]
> @JxM-92
> hello!
> i think you have there is typo error it not "p5.oscillator" it must be "p5.Oscillator"
> 
> and i have tested the osc.amp(Val) in the p5 web editor
> and i got nothing wrong!
> it just worked in both ways !
> but for the record and performance issue
> the first method is more appreciated !

thanks, but that was an example, not the actual code I was using...
Still got it figured out...
