### ISSUE TITLE
Testing Errors in p5.SoundFiles.js

### ISSUE THREAD

**Issue by endurance21** [processing/p5.js-sound#425]
getting following error while testing 
![testssoundfiles2](https://user-images.githubusercontent.com/43696525/76890405-513ffb80-68ad-11ea-8539-5e7bc8bf67f5.png)

if the test route is triggered for the very first time , then the test passes however , after refresh the same error is shown up!
also how does this test works ?
setting Volume to Zero at first place and then checking for a.getLevel for value between (0,3) is just not convincing !

![testssoundfiles](https://user-images.githubusercontent.com/43696525/76890621-b3006580-68ad-11ea-892a-0bf6e140254f.png)

**Comment by aceslowman** [comment]
Are you testing this in Chrome? I seem to be having issues with testing in Chrome due to their autoplay policy, is it possible that the tests need to be run only after user interaction / AudioContext.resume()?

**Comment by endurance21** [comment]
yes!
