### ISSUE TITLE
p5.sound.min.js.map

### ISSUE THREAD

**Issue by joepdooper** [processing/p5.js-sound#430]
I get the following error in the Safari console `Failed to load resource: the server responded with a status of 404 ()` and `https://cdn.jsdelivr.net/npm/p5/lib/addons/p5.sound.min.js.map` and in the Chrome console `DevTools failed to parse SourceMap: https://cdn.jsdelivr.net/npm/p5/lib/addons/p5.sound.min.js.map`

[p5.js version 0.10.2](https://cdn.jsdelivr.net/npm/p5)
[p5.sound version: 0.3.12](https://cdn.jsdelivr.net/npm/p5/lib/addons/p5.sound.min.js)

**Comment by endurance21** [comment]
@joepdooper can you please list from where you got those links to  Map files..?.
I mean is it there on p5.org?.

**Comment by joepdooper** [comment]
> @joepdooper can you please list from where you got those links to Map files..?.
> I mean is it there on p5.org?.

I don't understand your question. You mean the website that creates this error? This is the website at the moment: http://199907a4.ngrok.io/

**Comment by tpltnt** [comment]
The p5.js package from https://p5js.org/download/ yields this error.

**Comment by endurance21** [comment]
@joepdooper @tpltnt  what i can see that there is only this 
https://cdn.jsdelivr.net/npm/p5@1.0.0/lib/p5.min.js 
as name of CDN links

**Comment by joepdooper** [comment]
For some reason the error has disappeared… I'll close this issue if the error doesn't reappear.

**Comment by veirum** [comment]
I get the exact same error.

**Comment by zuppao** [comment]
me too, same problem.
In my case, I´m working on a little game and I am running all locally on my machine . I downloaded the libraryes from p5js.org

At the first, I wrote all the code (loops, interations, classes, etc) and test it..... All good.....
Then I started to work with sounds effects. I just included a ref to 'p5.sound.min.js' on head session of the html page and got the error:
"DevTools failed to parse SourceMap: http://localhost:3000/lib/p5/p5.sound.min.js.map"

I am using Sublime editor and running the page on Chrome (using Sublime "Browse Sync" package).

**Comment by joepdooper** [comment]
@zuppao Thank you! I downloaded the "Source code" zip file from https://github.com/processing/p5.js-sound/releases and indeed inside the 'Lib' folder it has the .map file! Great!

**Comment by RichardJECooke** [comment]
Hi, how do you fix this error please? I am getting it when using the files included in the 'Downloaded' link on the p5.js Web site. This is my first time using Processing.
`Could not read source map for file:///p5.sound.min.js:`

**Comment by zuppao** [comment]
> Hi, how do you fix this error please? I am getting it when using the files included in the 'Downloaded' link on the p5.js Web site. This is my first time using Processing.
> `Could not read source map for file:///p5.sound.min.js` There is no `p5.sound.min.js.map` in the downloaded zip file

@RichardJECooke buddy you need to download the missing files (.map) from the official github rep in https://github.com/processing/p5.js-sound/tree/master/lib then you will be abke to add it to your project (sorry for the delay on answer)

**Comment by ItzLarz** [comment]
I fixed the first error with your answers, but now I get this error: "DevTools failed to load source map: Could not parse content for https://itzlarz.dev/p5.sound.js.map: Unexpected token < in JSON at position 6"

Why is it trying to parse an HTML file as a JSON file?
