### ISSUE TITLE
require.js compatibility

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-sound#44]
We recently added Common JS and AMD checks to p5.sound. Gotta test this out and show some examples for how to load p5 + p5.sound with require.js.

I received an email from somebody who is trying to do it this way, and it wasn't working:

```
define(['p5', 'p5Sound'], function(p5, p5Sound) {
    'use strict';

    var myp5 = new p5(function(sketch) {
        //some app code here
    },'p5-canvas');

    var myp5Sound = new p5.Sound();
});
```

An issue may be that p5.sound doesn't return an object, and so does not have a constructor, but instead adds to the p5.prototype. I'm not sure how to fix this, but I'd love to come up with an example that shows how to load p5.sound with require.js.

**Comment by brysonian** [comment]
that's how dom was too, maybe you can copy how it is done there? https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js

**Comment by therewasaguy** [comment]
Thanks @brysonian! p5.sound is doing the same thing as p5.dom. I'm thinking the solution is just to ``require('p5Sound')``, but not to call ``new p5.Sound()`` ?

**Comment by brysonian** [comment]
I can get it working like this:

```javascript
require(["p5", "p5.sound"], function(p5) {
	var myp5 = new p5(function( sketch ) {
		var mySound;

		sketch.preload = function() {
			mySound = sketch.loadSound('demo.mp3');
		}

	  sketch.setup = function() {
	    var cnv = sketch.createCanvas(400, 400);
			mySound.loop();
	  }

	  sketch.draw = function() {

	  }
	}, 'sketch-div');
});
```

**Comment by rjbultitude** [comment]
I tried the way described above (amongst others) but get 
Uncaught TypeError: sketch.loadSound is not a function
I can see p5.sound has been loaded as a source, so I would expect it to load all the necessary methods as part of the p5 object's prototype, but they're just not available.
In the console when I watch the expression 'sketch' it returns the amdclean.core.p5 object and all p5's _proto_ methods and constants but the p5.sound ones are not properties of it.
I'm using p5.js v0.4.5 and p5.sound.js v0.2.1. 
Any help appreciated

**Comment by brysonian** [comment]
Interesting. I also get http://requirejs.org/docs/errors.html#mismatch when using p5.js 0.4.5 with p5.sound.js 0.2.11 using the above code. What is really peculiar is that changing the version of p5.js to 0.4.4 fixes it. 

A quick glance suggests that something about how the new type code is included is making AMD angry. Starting around https://github.com/processing/p5.js/blob/master/lib/p5.js#L7574 is seems like things go off the rails a bit, but i'm no AMD expert either. I'll try to take a deeper look later today.

**Comment by brysonian** [comment]
Pinging @kadamwhite who might have some insight.

**Comment by IsmaelMT** [comment]
Hello, I was trying to use p5.sound with require but the require statement is not loading the p5.sound script. 

var p5 = require("p5/lib/addons/p5.sound");

But then when I inspect p5 with console.log() I just get {}. I can load successfully the p5.js library but of course I don't have the audio functions I need. 

What's the status of this issue? Can you help me?

Thanks!

**Comment by rjbultitude** [comment]
Hi @IsmaelMT 
You do not need to assign P5 Sound to a variable, you just need to load and run it just like in @brysonian 's example above. I just ran his code to double check and it works perfectly.

@therewasaguy I think this issue can be closed. 

BTW I'm not using Require.js any more but it work for me using the Common JS pattern, which in terms of defining dependencies, works in a very similar way. It works for me both with P5 & P5 Sound as static files or via NPM.

**Comment by montoyamoraga** [comment]
closing this issue per recommendation of the last poster
