### ISSUE TITLE
NF_ERROR_FAILURE with onload in Firefox but not other browsers

### ISSUE THREAD

**Issue by gevhaz** [processing/p5.js-sound#442]
I think this is a bug. My sketch runs fine on Konqueror and Chromium but in Firefox, the Inspector reports this error:

```
NS_ERROR_FAILURE: p5.js:65186
    _applyDefaults https://www.<my-website>/p5/p5.js:65186
    createCanvas https://www.<my-website>/p5/p5.js:66805
    _setup https://www.<my-website>/p5/p5.js:63025
    _runIfPreloadsAreDone https://www.<my-website>/p5/p5.js:62986
    _decrementPreload https://www.<my-website>/p5/p5.js:62995
    s https://www.<my-website>/p5/addons/p5.sound.js:3550
    onload https://www.<my-website>/p5/addons/p5.sound.js:3589
```

## Intended behavior

Canvas should show my sketch.

## Actual behavior

Canvas is blank but clicking it starts playing the sound file (as it should, with my code).

**Comment by endurance21** [comment]
@gevhaz  can you please provide some more code details, it would give a more clear idea  on tracing the bug !

**Comment by gevhaz** [comment]
Thanks for the reply. Unfortunately, I can no longer reproduce the error. I don't think I've made any changes to my sketch so it was likely a problem with my own web page or the Firefox cache or settings.

Closing because I can no longer reproduce.
