### ISSUE TITLE
Need a perfect documentation for   p5.signal class !

### ISSUE THREAD

**Issue by endurance21** [processing/p5.js-sound#474]
https://p5js.org/reference/#/p5.Signal

The example here, no where uses the class p5.Signal  , it however uses the basics implementation behind it ! 
But an example elaborating the  use of P5.signal would really be helpful ! :grinning:

**Comment by montoyamoraga** [comment]
that is true, the example uses oscillator, which are built on top of p5.Signal, maybe an example which showed what is the barebones p5.Signal would be better, i assigned it to you :)

**Comment by endurance21** [comment]
@montoyamoraga  
i would love to submit an example for the same ! thanks ! :)

**Comment by montoyamoraga** [comment]
@endurance21 ok great, i assigned you this issue, and please mention it when you submit a pull request, and you can tag me as reviewer :)

**Comment by therewasaguy** [comment]
great idea, @endurance21, thank you for bringing this up!

I think it would be preferable to delete the p5.Signal as mentioned https://github.com/processing/p5.js-sound/issues/477#issuecomment-623851545

I'll close this issue for now and keep that one open to continue the discussion
