### ISSUE TITLE
delete older branches

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.js-sound#479]
hi!

i wanted to ask if we can remove old branches and keep only the relevant ones for current development?

i think branches 0.3.6, 0.3.8, 0.3.10, and therewasaguy-patch-1 can be deleted?
thoughts? :)

also, what about the branch gh-pages? is it being used for hosting some of the xamples at processing.github.io/p5.js-sound?

**Comment by therewasaguy** [comment]
gh-pages is used for examples, yes. But maybe we should use our master branch for gh-pages instead... let's delete the old branches, great idea!

**Comment by montoyamoraga** [comment]
i went through the old branches, and i deleted the ones that were safe to be deleted as marked by GitHub, since they were merged into master, we went from 15 branches to 8, yay
