### ISSUE TITLE
delete files from lib/ folder

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.js-sound#480]
hi!

there are a lot of files in the lib/ folder, including previous versions of p5.js and p5.dom.js,
should we only have p5.sound.js and p5.sound.min.js on that folder?

are these files put there manually or automatically when p5.sound.js is built?

**Comment by therewasaguy** [comment]
they are placed there manually, but it would be ideal to not check them into the repo or to keep them up-to-date. It's useful when testing examples locally. Perhaps the examples could points to the latest p5.js on the CDN? That might make it difficult to develop locally without internet, but hopefully if anyone is doing that they can prepare.

**Comment by montoyamoraga** [comment]
@therewasaguy yeah i am issuing a PR to delete some of the old files on lib/, so that when p5.sound.js is developed is never tested with old versions :)
