### ISSUE TITLE
Add Detune to p5.Oscillator

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-sound#49]
It can mirror the .freq() implementation here https://github.com/processing/p5.js-sound/blob/master/src/oscillator.js#L175
- store detune as a property of the oscillator
- provide access to [Web Audio API's oscillatorNode detune param](https://developer.mozilla.org/en-US/docs/Web/API/OscillatorNode/detune), and set that value to `this.detune` every time a new oscillator node is created (for example in `.start()`), just as we do for frequency. The reason is that Web Audio API requires creation of a new oscillator node every time it is stopped/started. But we want the p5.Oscillator to remember its frequency and detune param even after it is stopped.

**Comment by therewasaguy** [comment]
This is a low priority at the moment but a good issue for anyone looking for a place to get started contributing to the source code (more info [here](https://github.com/processing/p5.js-sound/wiki/Contribute))

**Comment by polyrhythmatic** [comment]
oops! @b2renger didn't mean to unassign you !

**Comment by montoyamoraga** [comment]
because of the low traction on this upgrade, i am closing this issue for now ~
