### ISSUE TITLE
Contributions to make to analysis tools?

### ISSUE THREAD

**Issue by aceslowman** [processing/p5.js-sound#504]
Hello! I've been looking to get start working on some of the tasks listed in the todo document and was curious what would be effective at this time. Is there still work being done to get offline versions of the analysis tools (peak, beat, pitch) working? The offline peak detection example doesn't seem to be functioning at the moment and I'd be interested in exploring the analysis tools in general. Happy to put some work into another part of the project if there is something that is more pressing.

**Comment by endurance21** [comment]
@aceslowman  most welcome 🙏
Currently the codebase is being revamped to es6 features!
Look at the recent commits, you ll get an idea. 
Its interesting to see such enthusiasm, however i would suggest that if you are to  contribute , do it in es6 style like use of classes, export/imports, let, const. 

Also you can work on testing part of our codebase, that even more interesting ❤️

**Comment by aceslowman** [comment]
I can definitely do some testing, and I'll dig through some of the recent commits. Are there any classes that would be a good starting place?  

Also I was curious as I just ran into this, is the transition to es6 that you mentioned related to issues with p5.sound when using npm? (see: #453)

**Comment by endurance21** [comment]
@aceslowman  nice find out ! 

so ya as per the issue #453 ,  I think the user must configure its webpack for using requireJs 




however  , earlier we have been using requireJs for making up our module system ! but  with this gsoc project , there will be no further use of "define" word or any of require js things !  in build folder! and no config would be required ! 

so you can wait until the next release or you can download the current non published code by simply cloning the this repo and building the lib files by using grunt !

**Comment by endurance21** [comment]
also if you want to start , I would suggest look into each and every p5sound  interfaces ( for example p5.oscillator , p5.audioIn ...etc)    and figure out which of those are lacking the  unit testing ( in test/ folder) 

https://github.com/processing/p5.js-sound/wiki/Contribute#testing 
this can be a of great use !

**Comment by endurance21** [comment]
@aceslowman  i think we are done here? time to close this issue?

**Comment by aceslowman** [comment]
Yes! Thank you.
