### ISSUE TITLE
.currentTime() returns 0 at all times

### ISSUE THREAD

**Issue by BrewHog** [processing/p5.js-sound#507]
/** [p5.sound]  Version: 0.3.12 - 2020-01-06 */ 

This might be related to the following issue (As it showed up in my code at the same time): https://github.com/processing/p5.js-sound/issues/506

When calling .currentTime() on a loaded sound (.loadSound()), the .currentTime() method always returns 0. This began occurring either yesterday or the day before and I could not find anyone else who has submitted this as a bug. 

Seems to happen on all current/stable versions of major browsers (Tested on Chrome and Firefox).

I'm testing on Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by endurance21** [comment]
@BrewHog  thanks for the patience, will look into the matter soon!

**Comment by MrRoboman** [comment]
I'm having this issue, too. Though, I think it may be a race condition because 1 out of 20 times currentTime() behaves correctly for me. Looks like `this._lastPos` is always set to 0 in the `currentTime` implementation, and it appears the callback that sets `this._lastPos` is not firing.
https://github.com/processing/p5.js-sound/blob/master/src/soundfile.js#L1353-L1364

**Comment by MrRoboman** [comment]
Figured it out! Here's a pull request to fix the issue, @endurance21 
https://github.com/processing/p5.js-sound/pull/542

**Comment by therewasaguy** [comment]
thanks again, @MrRoboman !

**Comment by therewasaguy** [comment]
and thank you for reporting, @BrewHog

**Comment by paraclete-pizza** [comment]
I am still having this issue, both with the sound library downloaded with from the main P5 site, as well as the more recent 1.0.0 version downloaded directly from GitHub. Why is this issue listed as 'closed'?

**Comment by rvacca2** [comment]
When I use FireFox the issue seems to go away, I only experience it when using Chrome.

**Comment by humanenver** [comment]
Still returning zero on Brave browser
