### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by b2renger** [processing/p5.js-sound#51]
I tested through all the examples, and some appears to be broken, here is a list of examples giving errors messages : 
- amplitude_analysis/
  Uncaught TypeError: Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'.t.SoundFile.load @ p5.sound.min.js:3t.SoundFile @ p5.sound.min.js:3t.loadSound @ p5.sound.min.js:3(anonymous function) @ p5.js:220amdclean.core.p5._start._preloadMethods.forEach.context.(anonymous function) @ p5.js:193preload @ sketch.js:18(anonymous function) @ p5.js:196amdclean.core.p5 @ p5.js:360amdclean.src_app._globalInit @ p5.js:7484
- granular_sampler/
  
  > p5.js says: image was expecting a p5.image for parameter #1, received [object Object] instead. image takes different numbers of parameters depending on what you want to do. Click this link to learn more: [http://p5js.org/reference/#p5/image]
  > sketch.js:111 Uncaught TypeError: Cannot read property 'gain' of undefined
- loadSound_With_Drag_and_Drop/
  Uncaught ReferenceError: createFileInput is not definedsetup @ sketch.js:21(anonymous function) @ p5.js:230(anonymous function) @ p5.js:203amdclean.core.p5 @ p5.js:360amdclean.src_app._globalInit @ p5.js:7484
- oscillator_FMSynth/
  Uncaught TypeError: undefined is not a functionsetup @ sketch.js:25(anonymous function) @ p5.js:230(anonymous function) @ p5.js:203amdclean.core.p5 @ p5.js:360amdclean.src_app._globalInit @ p5.js:7484
- play_soundfile/
  Uncaught TypeError: Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'.t.SoundFile.load @ p5.sound.min.js:3t.SoundFile @ p5.sound.min.js:3t.loadSound @ p5.sound.min.js:3setup @ sketch.js:13(anonymous function) @ p5.min.js:1(anonymous function) @ p5.min.js:1amdclean.core.d @ p5.min.js:1amdclean.src_app.S @ p5.min.js:5
- soundfile_playMode/
  Uncaught TypeError: Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'.t.SoundFile.load @ p5.sound.min.js:3t.SoundFile @ p5.sound.min.js:3t.loadSound @ p5.sound.min.js:3setup @ sketch.js:12(anonymous function) @ p5.js:230(anonymous function) @ p5.js:203amdclean.core.p5 @ p5.js:360amdclean.src_app._globalInit @ p5.js:7484

**Comment by therewasaguy** [comment]
Thanks @b2renger ! Will look into these.

**Comment by therewasaguy** [comment]
for loadSound_With_Drag_and_Drop, check your version of p5.dom

https://raw.githubusercontent.com/processing/p5.js-sound/master/lib/addons/p5.dom.js

The issues about 'readAsArrayBuffer' had to do with new ability to load sound by drag and drop, conflicting with loadSound with an array of files. Both will work in my next pull request.

Still need to work on granular sampler and oscillator_FMSynth

**Comment by b2renger** [comment]
don't bother with the granular sampler as it will probably revamped in an unknown way yet !

**Comment by montoyamoraga** [comment]
because of the current changes being done both at the source code of the library,
and the examples, i am closing this issue ~
