### ISSUE TITLE
p5.Oscillator.scale(), add(), and mult(), not working as expected

### ISSUE THREAD

**Issue by aceslowman** [processing/p5.js-sound#513]
Working through testing some of the undocumented methods in p5.Oscillator and ran into `scale(inMin,inMax,outMin,outMax)`. I would expect to be able to do the following, scaling amplitudes from 0 - 1 to 0.25 - 0.75:
```
it('can scale osc amplitude', function (done) {
      osc.amp(1);
      osc.start();
      expect(osc.getAmp()).to.equal(1);
      osc.scale(0, 1, 0.25, 0.75);

      setTimeout(function () {
        expect(osc.getAmp()).to.equal(0.75); // fails (osc.getAmp()==1)
        osc.stop();
        done();
      }, 50);
});
```
This fails with `osc.getAmp()` returning 1.0, apparently not being affected by the scale(). 

I have also tried this method outside of the test. When using `osc.scale(0,1,0,0.75)` within draw() I receive the following error:
```
p5.sound.js:170 Uncaught TypeError: Cannot read property 'disconnect' of null
    at i.Scale.a.disconnect (p5.sound.js:170)
    at sigChain (oscillator.js:475)
    at p5.SinOsc.p5.Oscillator.scale (oscillator.js:548)
    at draw (sketch.js:68)
    at p5._main.default.redraw (p5.js:70410)
    at _draw (p5.js:63106)
```

this goes for `p5.Oscillator.mult()` and `p5.Oscillator.add()`, with sigChain as the common issue.

**Comment by endurance21** [comment]
@aceslowman it would of great help if you please mention whhich branch / version of library you are testing?

**Comment by aceslowman** [comment]
Of course! Sorry about that. This is on the up-to-date master branch using p5 v1.1.9.

**Comment by endurance21** [comment]
@aceslowman  thanks for the confirmation, will look into soon!!
Have you tried going down there in src/oscillator.js and figure out is making it so!!

**Comment by aceslowman** [comment]
I've done some digging but I so far haven't quite made sense of how `sigChain()` is constructed and used, particularly how mathOps are connected and disconnected. I'll 

When scale is called, arguments are sent to ToneJS.Scale() and then to sigChain() where the problem occurs.

```
p5.Oscillator.prototype.scale = function (inMin, inMax, outMin, outMax) {
  var mapOutMin, mapOutMax;
  if (arguments.length === 4) {
    mapOutMin = p5.prototype.map(outMin, inMin, inMax, 0, 1) - 0.5;
    mapOutMax = p5.prototype.map(outMax, inMin, inMax, 0, 1) - 0.5;
  } else {
    mapOutMin = arguments[0];
    mapOutMax = arguments[1];
  }
  var scale = new Scale(mapOutMin, mapOutMax);
  var thisChain = this.mathOps.length - 1;
  var nextChain = this.output;  
  return sigChain(this, scale, thisChain, nextChain, Scale);

  // this.output.disconnect();
  // this.output.connect(scale)
};
```

`sigChain()` fails once when `chainSource` is set to an i.Scale node, which happens after hitting a conditional near the end of the following:

```
var sigChain = function (o, mathObj, thisChain, nextChain, type) {
  var chainSource = o.oscillator;
  // if this type of math already exists in the chain, replace it
  for (var i in o.mathOps) {
    if (o.mathOps[i] instanceof type) {
      chainSource.disconnect();
      o.mathOps[i].dispose();
      thisChain = i;
      // assume nextChain is output gain node unless...
      if (thisChain < o.mathOps.length - 2) {
        nextChain = o.mathOps[i + 1];
      }
    }
  }
  if (thisChain === o.mathOps.length - 1) {
    o.mathOps.push(nextChain);
  }
  // assume source is the oscillator unless i > 0
  if (i > 0) {
    // commenting out this line restores scale functionality
    // chainSource = o.mathOps[i - 1];
  }

  chainSource.disconnect();
  chainSource.connect(mathObj);
  mathObj.connect(nextChain);
  o.mathOps[thisChain] = mathObj;
  return o;
};
```

The error disappears if you comment out this conditional and the signal does begin to scale, add, and multiply, but it then becomes impossible to add multiple mathOps and the sound becomes noisy. Is it possible that these functions don't work well in the draw() loop? 

I'll key digging around with this but I figured I'd share what I've found so far.

**Comment by endurance21** [comment]
@aceslowman great find , right now we are little busy with the gsoc projects , we ll have a deep insight once we are done there .
one more thing i would suggest , have you tried this with , other version of the lib, one which is hosted on cdn ?
https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.1.9/addons/p5.sound.min.js

**Comment by endurance21** [comment]
@aceslowman what's the status of this issue ?

**Comment by yifanmai** [comment]
I'm a new contributor and I'm interested in fixing this issue. I've sent #653 to improve the state of things. However I'm unsure if this API is a good idea to begin with, because the API has non-intuitive gotchas:

```
// osc1 and osc2 are not equivalent becuase they have different node orders.
osc1.add(1).mult(2);
osc2.mult(2).add(1);

// osc1 and osc2 are equivalent, but osc3 is not equivalent with either.
// The node order is fixed by the initial method calls and cannot be changed.
osc1.add(2).mult(3);
osc2.add(1).mult(1).add(2).mult(3);
osc2.mult(1).add(1).add(2).mult(3);

// osc1 and osc2 are equivalent and scale by a factor of 2.
// osc3 scales by a factor of 4, because mult and scale are independent operations
osc1.mult(2);
osc2.scale(0, 1, 0, 2);
osc3.mult(2).scale(0, 1, 0, 2);
```

Additionally, there are browser-dependent performance issues when this is used in the `draw()` loop. This is because whenever one of these methods is called, the implementation creates a new replacement audio node, disconnects the old audio node from the signal chain, and connects the replacement audio node. This can be expensive. I tested this on Firefox 78 and Chrome 96 on Linux. Firefox worked fine but Chrome produced audio artifacts.

**Comment by davepagurek** [comment]
Agreed with the above assessment that the API could maybe use some thinking, to make order of operations more predictable. Maybe if we come up with some example usages that we want to support, we can make a new issue to discuss some ways to support those use cases with a more intuitive API?
