### ISSUE TITLE
p5.score doesn't work

### ISSUE THREAD

**Issue by MikhaelOP9** [processing/p5.js-sound#529]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- X Sound

#### Details about the bug:

- p5.js version: /** [p5.sound]  Version: 0.3.12 - 2020-06-26 */ 
- Web browser and version: Firefox 79
- Operating System: Windows
- Steps to reproduce this: the p5.score (sound) doesn't function

**Comment by therewasaguy** [comment]
this should be resolved with #543
