### ISSUE TITLE
loadSound not working in Safari in newest versions of library

### ISSUE THREAD

**Issue by cn-yn** [processing/p5.js-sound#55]
Been using the new versions of the library which fixed the Chrome output issue, but I think there might now be an issue with loading sounds in Safari. Slowly stripped my code down to just loading a sound and playing it in setup() - no sound - then swapped in an older version of p5.sound from February and it worked again. Tested a couple places it seems to be consistent. Weirdly there's no GET error - so I'm not sure what's going on.

**Comment by therewasaguy** [comment]
Thanks for the bug report, this should fix it:

But this fix temporarily takes away the ability to set the amp of individual buffer source nodes without changing the overall amp of any buffer source nodes that are still playing if the soundfile playmode is set to 'sustain'.

**Comment by cn-yn** [comment]
Gotcha - working great now - very much appreciated - thanks!
