### ISSUE TITLE
https://p5js.org/reference/#/p5.AudioIn/getSources 404 error

### ISSUE THREAD

**Issue by paulks-software** [processing/p5.js-sound#553]
404 error on mozilla link
https://p5js.org/reference/#/p5.AudioIn/getSources
and i get , how to list all devices?

This browser does not support MediaStreamTrack.getSources()
(index):86 Uncaught TypeError: Cannot read property 'getSources' of undefined
    at e.div.setup ((index):86)
    at e.<anonymous> (p5.min.js:4)
    at e.<anonymous> (p5.min.js:4)
div.setup @ (index):86
(anonymous) @ p5.min.js:4
(anonymous) @ p5.min.js:4
load (async)
e @ p5.min.js:5
(anonymous) @ (index):102

#### Most appropriate sub-area of p5.js?

- [x ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [x ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by PaulKsi** [comment]
Close it, sorry, found the issue

**Comment by PaulKsi** [comment]
But you can update the website ofc

**Comment by montoyamoraga** [comment]
closed per recommendation of the last poster
