### ISSUE TITLE
Sound reaction on Safari iPhone 6, works only with headphones or speakers

### ISSUE THREAD

**Issue by bianchinicecilia** [processing/p5.js-sound#562]
Hi all, I've a sketch with a 2D sound reaction and an Obj. When on iPhone Safari the audio works only on speakers or headphones. Works properly on Android. 

Here's the project I'm working on:
https://holly-jolly-world.ceciliabianchini.com/

Any idea on how to solve it? Thanks in advance :)

**Comment by datramt** [comment]
Hi! Have you made sure that your phone is not set to silence? I get sound on my iPhone from your sketch.

**Comment by bianchinicecilia** [comment]
Hey, you're very right. With no silent mode it works, thanks! Just wondering if there's a way to make it working in silent mode too? Just in case who receive it will have silent mode on.

**Comment by bianchinicecilia** [comment]
I just found a post from last year talking about the same issue, linking some workarounds to solve it:
https://github.com/processing/p5.js/issues/3907#issuecomment-518062666
