### ISSUE TITLE
pre-commit hook not working properly 

### ISSUE THREAD

**Issue by frappelatte28** [processing/p5.js-sound#569]
### current behavior
 the codebase is using `grunt-githooks ` that runs grunt lint to test any linting errors before letting developer to make a commit,
the thing is `grunt lint` corrects linting errors but it does not stop commit process,  changes made by linter remain in the working directory!

### expected behavior
it must prompt the developer to add the linting changes to the commit as well or should simply terminate the commit process.

*Also I would like to work on this issue*

**Comment by endurance21** [comment]
@frappelatte28 i agree with you , our pre commit hook system must be more robust , following are some more issues regarding the same!
* Currently linter `fixes` the linting mistakes automatically  in pre-commit hook :-
  * An easy fix i can think of is run the linter in `no-fix` mode when used in pre-commit hook, you can make two different task with grunt one for `lint fix` and other for `lint no-fix` you can read [here](https://gruntjs.com/api/grunt.task) about adding tasks to grunt.
* Secondly linter fixes linting errors on file other than `sraged-files` too,
   *  you can fix it by making a template for pre-commit hook that will stash other changes and then run linter and then pop stash chanegs   back to original state ! , [here](https://www.viget.com/articles/grunt-getting-started-with-git-hooks/) is the great article about it .
   
As it reflects , you know pretty much about pre-commit hook system, so go ahead.We welcome every contribution.
For any query , you can reach out to us here!

@montoyamoraga  @therewasaguy  @kyle1james  what do you think about it ?

**Comment by endurance21** [comment]
I think this has been adressed already.
In #574 @frappelatte28 

Closing this one .
