### ISSUE TITLE
Time for a release? 

### ISSUE THREAD

**Issue by rbtcollins** [processing/p5.js-sound#570]
7 months since the last one, 91 commits, including bugfixes such as #542

**Comment by lounge-chair** [comment]
I would also greatly benefit from an updated release, mainly due to the bugfix listed above.

**Comment by joepdooper** [comment]
Yes please!

**Comment by luan007** [comment]
Please, as current version still output error messages during init (usable though)

**Comment by montoyamoraga** [comment]
@therewasaguy @endurance21 thoughts? happy to help, i haven't helped with a release yet :)

**Comment by endurance21** [comment]
@montoyamoraga we are on our way for this,  actually point of stuck we have is ,
https://github.com/processing/p5.js-sound/pull/487 this pr .
I am bit off work these 2 days , hope to revive this pr asap.


Apart from this work , we are all set for the new release .

**Comment by montoyamoraga** [comment]
@endurance21 yay, super excited about it ~
good luck with everything, and thank you!

**Comment by montoyamoraga** [comment]
also, @endurance21 with the new release, could we please rename the branch "master" to "main" :)

https://github.com/github/renaming
https://cdm.link/2020/06/lets-dump-master-slave-terms/

**Comment by endurance21** [comment]
@montoyamoraga ya , for sure for better .
I will rename them .

**Comment by endurance21** [comment]
@montoyamoraga 
when is the new version of p5.js is releasing , we have to make a pr to the codebase of p5.js

**Comment by montoyamoraga** [comment]
@endurance21 the new version of p5.js or p5.sound.js?
i'm guessing p5.sound.js :)
do you think we should update stuff on p5.js? or the website?
happy to help ~

**Comment by endurance21** [comment]
when will the changes in p5.js are going to reflect on main website , i meant.
Before that we should add new p5.sound to the main website ?

**Comment by montoyamoraga** [comment]
@endurance21 apart from the download section,
i don't think there is another place that needs an update,
and my guess is that is handled automatically when a new release of p5.js happens on the main repo?
we should ask and i would add all the necesary steps on our contributors docs,
maybe here?
https://github.com/processing/p5.js/blob/main/contributor_docs/release_process.md

**Comment by paulcanning** [comment]
Any movement on this?

**Comment by therewasaguy** [comment]
new release is coming soon https://github.com/processing/p5.js/pull/5266

adding documentation here for how to release a new versionhttps://github.com/processing/p5.js-sound/wiki/Releasing-a-new-version-of-p5.sound-library

and thanks @montoyamoraga for this link! Do you know if this means anyone can release a version of p5.js? https://github.com/processing/p5.js/blob/main/contributor_docs/release_process.md

**Comment by montoyamoraga** [comment]
as i understand it, you gotta have push access to the repo to do a release, and if you don't, you can still try it and make sure everything is working OK on your machine without publishing to GitHub or npm, right? :)
