### ISSUE TITLE
p5.SoundFile example has more width than other examples

### ISSUE THREAD

**Issue by Rahulm2310** [processing/p5.js-sound#588]
**Actual Behaviour**
Width of p5.SoundFile example has more width than all other examples 
 

 **Expected Behaviour**
Its width should also be same as all other examples
 

 

 **Screenshots of the issue**
**p5.SoundFile:**

![p5soundfilewidtherror](https://user-images.githubusercontent.com/54268438/79858651-5f71c200-83ed-11ea-95a7-227eca22b352.gif)

**Other examples:**

![p5 soundwidtherror1](https://user-images.githubusercontent.com/54268438/79856943-a6aa8380-83ea-11ea-9c6e-ef5231a1505d.gif)

 

 **Would you like to work on the issue?**
YES

**Comment by montoyamoraga** [comment]
as of 2023, this was fixed, so i am closing it
