### ISSUE TITLE
AudioWorklet issues

### ISSUE THREAD

**Issue by endurance21** [processing/p5.js-sound#592]
getting following error while runnings p5.oscillattor inline example :-
`
:9001/docs/reference/#/p5.Oscillator:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"recorder-processor" is already registered.
    at blob:http://127.0.0.1:9001/fe89e6fb-9435-4561-a562-9bcbf4482a8c:279:1
`
browser : chrome 88.0.4324.1

**Comment by endurance21** [comment]
@therewasaguy was trying to check the reference page on p5.js with latest p5.sound build , turns out smth is broken ?

**Comment by oshoham** [comment]
@endurance21 That error message suggests that p5.js-sound is attempting to load the AudioWorklet modules multiple times.

I looked through the commit history for AudioWorklet-related code and I noticed that you removed an `if` statement in the AudioWorklet loading logic that was meant to prevent this bug from happening: https://github.com/processing/p5.js-sound/commit/2fd6a9012f0e0ea4bb70a6ca784661674e453fc3#diff-b30b30ac6d5311c62f1ef8f4feac8c0936620ac5a494635c48d263d768f3d347

Here's the commit where @therewasaguy added that code originally to solve this problem: https://github.com/processing/p5.js-sound/commit/7f89c853da9fe45e170927f93b5d828f571db68d#diff-b30b30ac6d5311c62f1ef8f4feac8c0936620ac5a494635c48d263d768f3d347

**Comment by endurance21** [comment]
@oshoham i might have removed this while i was removing my promise setup .
Anyways thank you for helping out !
i will make the change soon

**Comment by andreasvirkus** [comment]
Hi, has this change been released? I'm getting the same error (and multiple similar ones) on `1.3.1`

```html
<script src="https://cdn.jsdelivr.net/npm/p5@1.3.1/lib/p5.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/p5@1.3.1/lib/addons/p5.sound.min.js"></script>
```

And the errors:

```javascript
Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"recorder-processor" is already registered.
    at blob:https://localhost:5000/aa260080-48fe-43e1-bf34-4b0635476f53:279:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"sound-file-processor" is already registered.
    at blob:https://localhost:5000/e1543f66-277e-4ef2-86d7-59e54747302e:189:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"amplitude-processor" is already registered.
    at blob:https://localhost:5000/4f3ac466-f6ff-4883-b8cd-edb7978fed49:252:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"recorder-processor" is already registered.
    at blob:https://localhost:5000/5b14522c-3d1e-4fd0-9268-ab8f939de37d:279:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"sound-file-processor" is already registered.
    at blob:https://localhost:5000/3711d687-c8cf-42c2-a598-7e4838ac2eab:189:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"amplitude-processor" is already registered.
    at blob:https://localhost:5000/4b4d8f95-5067-4923-9f58-902926689aab:252:1
```

**Comment by endurance21** [comment]
@therewasaguy  are we planning to release the latest version soon ?

**Comment by therewasaguy** [comment]
@andreasvirkus what version of p5.sound? It has its own version, separate from p5.

The new release (1.0.1) should be coming with the next version of p5.js in about a week, you can follow along here https://github.com/processing/p5.js/pull/5266

Or download the p5 sound release now from https://github.com/processing/p5.js-sound/releases

**Comment by andreasvirkus** [comment]
All the versions of p5, from `p5@1.3.1` down to `p5@0.10.2` include `p5.sound@0.3.12` in the CDN:
https://cdn.jsdelivr.net/npm/p5@1.3.1/lib/addons/

Thanks, I'll include it locally for now 🙌   Would it be possible to host this package's latest versions on a CDN as well? I'd love to include it via [Skypack](https://www.skypack.dev/) as you've now refactored it as ESM :3

**Comment by andreasvirkus** [comment]
Sorry, but still getting the same error with `1.0.1`

```
Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"sound-file-processor" is already registered.
    at blob:https://localhost:5000/ab8b4ff2-3a91-4960-bd2e-e7768b323dec:189:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"recorder-processor" is already registered.
    at blob:https://localhost:5000/01661d41-3e56-488b-a3f9-3e02190722d8:279:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"sound-file-processor" is already registered.
    at blob:https://localhost:5000/c4f18196-81e4-4a85-9680-579b080b7234:189:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"amplitude-processor" is already registered.
    at blob:https://localhost:5000/19c5e8c7-423d-4daa-a4a7-d04a4b6099e3:252:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"recorder-processor" is already registered.
    at blob:https://localhost:5000/eff48df9-7025-4f9f-b91e-52e14e9570b4:279:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"sound-file-processor" is already registered.
    at blob:https://localhost:5000/dcabef16-3887-4da4-8d5e-37ceb91c7f16:189:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"amplitude-processor" is already registered.
    at blob:https://localhost:5000/04e01a88-9ab4-4d77-b10f-4a470aff6d61:252:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"recorder-processor" is already registered.
    at blob:https://localhost:5000/89a63dee-b27b-4068-8b2e-7b01d6f40407:279:1
localhost/:1 Uncaught DOMException: Failed to execute 'registerProcessor' on 'AudioWorkletGlobalScope': An AudioWorkletProcessor with name:"amplitude-processor" is already registered.
    at blob:https://localhost:5000/a72eb75c-3617-40e6-9143-080a0a4991b6:252:1
```

And another note, once the new p5.sound would be released with p5 - how would including it natively as ESModules look like? If i currently run

```javascript
import p5 from 'https://cdn.skypack.dev/p5'
import '../vendor/p5.sound.js' // 1.0.1
```

Then p5.sound errors out, as it cannot find `p5` from the global context - so p5 would still have to be included via a script tag, missing out on async imports, etc.

**Comment by endurance21** [comment]
@andreasvirkus 
The bug has been fixed already in #593 .
Have you rechecked by some means if older version is cached or smth in the project ?

**Comment by endurance21** [comment]
Also you can try instance mode of using p5 if you don't want to keep it as global var :) 
Refere here 
https://github.com/processing/p5.js/wiki/Global-and-instance-mode

**Comment by andreasvirkus** [comment]
Interesting, when I had the error, I checked the version from the Network tab and the `p5.sound.js` file started with
```
/** [p5.sound]  Version: 1.0.1 - 2021-05-25 */ 
```

But retesting it now, `1.0.1` works fine 🤔 

-----

Thanks, I am using it in instance mode already, but since `p5.sound` can't be loaded natively as an ESModule (as it looks for `window.p5`), then I have to load them both via script tags, which still places `p5` into the global scope.

**Comment by DanBennettDev** [comment]
Hi, I'm currently getting this error if I run two different sketches in instance mode. One of them does not use audio at all.
This is with sound Version: 1.0.1 - 2021-05-25 and p5.js v1.4.0 June 29, 2021

**Comment by niki-ito** [comment]
Hello. The error appears in the console for me as well with the instance mode. I do use audio but the audio itself runs fine. The error doesn't seem to be causing any issues in my p5 sketch. 
I am also using version: 1.0.1

**Comment by DanBennettDev** [comment]
Thanks for the input Niki. I'm *pretty* sure I was missing audio too. But could be wrong, and could have been missing something else...  
I've not got time to investigate this again in the next few days but I'll post back later next week when I'm back on this project.

**Comment by B3njimin** [comment]
Hello, I am also experiencing this error message, specifically when using multiple canvasas in instance mode.

I'm running the sketch on a local host and used the latest p5 sound min.
