### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by pyroxenite** [processing/p5.js-sound#634]
There's a typo in the reference here:
https://p5js.org/reference/#/p5.Panner3D
"Connect an audio sorce"
Have a nice day

**Comment by code4humanity** [comment]
@pyroxenite, do you want to fix this typo? In the case you don't want, I can do so.

**Comment by pyroxenite** [comment]
Sure! I'll have to learn how to issue pull requests first haha

**Comment by code4humanity** [comment]
If you need anything, I'm glad to help
