### ISSUE TITLE
Distortion/glitching after hundreds of calls to SoundFile.play()

### ISSUE THREAD

**Issue by apc518** [processing/p5.js-sound#647]
This is likely related to #494 but I have a minimal example with some more detailed testing. Also, a user said [here](https://github.com/processing/p5.js-sound/issues/494#issuecomment-834502062) that updating to chrome 92 fixed the issue but I've tested this in chrome 94 and its still there.

Version: 1.4.0
Behavior: distortion, choppiness, glitchiness of sounds after calling the `SoundFile.play()` method hundreds of times.

[minimal reproduction](https://editor.p5js.org/apc518/sketches/BZ54TNZ3b)

Interestingly, this issue is not present on version 0.6.1. However, 0.6.1 has a big memory leak issue on Firefox.

setups tested:
FIREFOX on LINUX MINT 20.2 on a Lenovo Ideapad 5
CHROMIUM on LINUX MINT 20.2 on a Lenovo Ideapad 5
FIREFOX on WINDOWS 10 on a custom PC (Ryzen 5 2600)
GOOGLE CHROME on WINDOWS 10 on a custom PC (Ryzen 5 2600)
BRAVE on ANDROID 11 on Samsung Galaxy A32

Really the only setup variable missing is Apple products. I don't have any ¯\_(ツ)_/¯

while different setups exhibited different counts before distortion all setups eventually did distort and get worse from there. While each setup was consistent test to test initially, I did observe different counts-before-distortion day-to-day, and I was able to get the distortion to come a little earlier by opening a lot of applications and tabs on my computer. So it might be a memory related thing.

calling `stop()` on a file before playing it doesn't prevent distortion (though this wouldn't be ideal anyway since it would disallow a sound overlapping itself, which is kind of the point of having a library to play sounds like this)

As in #494, it was worst on mobile. Firefox lasted longer before distorting on Windows, chromium lasted longer on Linux.

I tested letting each sound run to completion before playing it again vs letting a sound overlap itself.
I also tested playing multiple different sounds at once vs playing one at a time.
I tested all four combinations of these two parameters, none of which seem to make a difference to how many `play()` calls were made before distortion kicked in.

**Comment by hedbergj** [comment]
Reproduces on Chrome 94 on Mac OS 11.2.3
but does not reproduce on Safari 14 Mac OS 11.2.3 (though I only could take about 2000 frames before stopping it :)

**Comment by zenzoa** [comment]
I'm seeing this bug in my game (https://github.com/zenzoa/bunbons). Has anyone made progress in fixing this or coming up with a workaround?

**Comment by TylerAlesse** [comment]
Seeing this as well, using Firefox 98.0.2 (64-bit), Ubuntu 20.04.4 LTS (64-bit).
