### ISSUE TITLE
Can't set distortion amount to 0 via set() method

### ISSUE THREAD

**Issue by GHSam** [processing/p5.js-sound#652]
The documentation says amount should be a value between 0-1 but isn't possible to set the distortion amount to 0 via the `set()` method as it checks the truthy value of the amount argument:
https://github.com/processing/p5.js-sound/blob/1a9beda8528095e410a45b8822cbd846bba810df/src/distortion.js#L98

When amount is 0 it's false.

It is possible to set amount to 0 via the constructor as that checks for `undefined` instead of a truthy value.

**Comment by KevinGrajeda** [comment]
@davepagurek this issue could be closed

**Comment by davepagurek** [comment]
Thanks @KevinGrajeda!
