### ISSUE TITLE
CORS error on loading a song from url.

### ISSUE THREAD

**Issue by Jrkej** [processing/p5.js-sound#654]
I was trying to load a song from a url but gives me the CORS error - 
![image](https://user-images.githubusercontent.com/64839659/148356002-0a9ee600-f55a-430a-b59c-73743faa1a32.png)
Code - 
```
let url = "https://malpha.123tokyo.xyz/get.php/f/98/CtgD91Ev4NU.mp3?cid=MTczLjI0OS4xMC4yMjIsMTczLjI0OS4xMC4yMjJ8R28taHR0cC1jbGllbnQvMS4xfERF&h=bpV5rGEBlKfcLqfpaO_U2Q&s=1641466012&n=Rozana-Full-Video-Song-Naam-Shabana-Akshay-Kumar-Taapsee-Pannu-Taher-Shabbir-I-Shreya-Rochak"
song = loadSound(url)
```
In which url is the link for the song `.mp3`
For now i got to know this error is caused due to something missing in headers in request.
Please tell me a way out of it!
Thanks in advance!!

**Comment by lf32** [comment]
It appears that the file is no longer available on the host URL, as it displays a `410 Gone Error,` and if you are having problems with the header, this might help you.

[CORS header 'Access-Control-Allow-Origin' missing on MDN Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin)

**Comment by montoyamoraga** [comment]
because of the last issue, my guess is that issue has to do with the .mp3 file, not the library,
so i am closing it for now ~
