### ISSUE TITLE
 * Tone.js r10 *  addons/p5.sound.js:125 Uncaught DOMException: The user aborted a request.

### ISSUE THREAD

**Issue by Falling10fruit** [processing/p5.js-sound#657]
I downloaded the latest version of p5 (v 1.4.1) and simply uncommented the script tag in the empty example. And this error appeared:
 * Tone.js r10 * 
addons/p5.sound.js:125
Uncaught DOMException: The user aborted a request.

I'm using:

- Windows 10 (v 21H1)
- VSCode (v 1.65)
- Microsoft Edge (v 99.0.1150.46 (Official build) (64-bit))

**Comment by Falling10fruit** [comment]
How do you add labels?

**Comment by montoyamoraga** [comment]
hi! we don't know what empty example you are referring to, but we tested the editor and p5.sound.js is working ~
