### ISSUE TITLE
Changing osc type in MonoSynth

### ISSUE THREAD

**Issue by KevinGrajeda** [processing/p5.js-sound#663]
Is there a reason why you can't change the oscillator type of the monosynth directly? 
like through the constructor or a setType function

**Comment by KevinGrajeda** [comment]
@davepagurek do you think it's a good idea to add `setType(type)` and `getType()` for MonoSynth.
inside monosynth.js we would only have to add
```javascript
setType(type) {
  this.oscillator.setType(type);
}
getType() {
  return this.oscillator.getType();
}
```
let me know your opinion

**Comment by davepagurek** [comment]
I think it's ok for MonoSynth! Although, if you use the classes in here https://github.com/processing/p5.js-sound/blob/main/src/oscillator.js#L586-L628, you can end up in an odd situation like this, where the class and its actual type give conflicting information:
```js
const osc = new TriOsc();
osc.setType('triangle');
console.log(osc.getType()); // triangle
console.log(osc instanceof TriOsc); // true
```

So maybe in general we should be trying to shift away from those in favor of the `Oscillator` class. But anyway, I think for MonoSynth it's pretty safe, as it doesn't use one of those subclasses internally.
