### ISSUE TITLE
Playing p5.SoundFile on windows phone 8.1

### ISSUE THREAD

**Issue by karneaud** [processing/p5.js-sound#68]
Tried using the p5.Sound on my windows mobile phone version 8.1 and I don't seem to be getting anything...is it like the iOS where you have to have user input to play?

**Comment by karneaud** [comment]
doing some debugging and using the following https://fiddle.jshell.net/gnyvo9b5/24/show/

when executing 

`function preload()
{
    try
    {
    song = loadSound('https://api.soundcloud.com/tracks/99707944/stream?client_id=b70992a44396c31917788bfd43b6d99f');
    }catch(err)
        {
            alert(err.message);
           // preload();
        }
}
`
I get an error "loadSound" undefined.

**Comment by therewasaguy** [comment]
I'm guessing that p5.sound is not loading on windows mobile because p5.sound uses the Web Audio API, which is not supported yet in Internet Explorer. http://caniuse.com/#feat=audio-api

If you just want to play sound, try the createAudio method of the p5.dom addon, which creates an HTML5 Audio element http://p5js.org/reference/#/p5/createAudio

**Comment by karneaud** [comment]
yeah saw this....however was quite baffled by the error. Anyways....think i'll fork your repo and try to come up with an alternative to use create Audio as a fallback.

**Comment by karneaud** [comment]
Question why did it say loadSound undefined? why not something else like "web audio not supported" when trying to instantiate the object?

**Comment by therewasaguy** [comment]
Great question, @karneaud! There should be friendlier error messages and the ability for the developer to customize a message for the user if their browser doesn't support the Web Audio API. I'll make a new issue for that.
