### ISSUE TITLE
Error message when Web Audio is not supported

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-sound#69]
p5.sound throws cryptic errors when Web Audio is not supported, like "loadSound is not defined" as mentioned in https://github.com/processing/p5.js-sound/issues/68.

Instead, it should first check if Web Audio is supported, and if not, log this message. Something like "The Web Audio API is not supported by this web browser. For a list of supported browsers, visit http://caniuse.com/#feat=audio-api." 

Ideally we'd allow the developer to provide a custom function to help point users in the right direction when their browser doesn't support the Web Audio API. Basically, an optional error handler/callback function when web audio is not supported. Something like `webAudioNotSupported(callback)` ?

**Comment by rjbultitude** [comment]
Hi @therewasaguy . Is someone working on this or should I take a look?

**Comment by therewasaguy** [comment]
@rjbultitude that would be great! Feel free to use this issues threat to share your progress or invite discussion.

**Comment by rjbultitude** [comment]
Hi @therewasaguy. So far I've just added this code above the first p5.sound module (sndcore) 

`if (!window.AudioContext || !window.webkitAudioContext) {
   console.error('No Audio Context');
   p5.prototype.noWebAudioCtx = function noWebAudioCtxFn(_callback) {
    _callback();
   }
  return false;
}`

which puts a stop to the cryptic p5Sound errors, provides a clearer one and offers a some kind of error handler. However, in my app I'm loading P5 using the Common JS API and consequently have to create an instance of it before being able to work with any of the properties or methods e.g. `var myP5 = new P5(function(sketch) { //my app code here`. Any suggestions on how to create a useful error handler welcome.

**Comment by montoyamoraga** [comment]
because of the staleness of this issue, i am closing it for now ~
