### ISSUE TITLE
How to combine SoundFiles?

### ISSUE THREAD

**Issue by togakangaroo** [processing/p5.js-sound#70]
I'm taking some students through making a very simple looping machine using p5. We can create and control samples and play them at the same time.

The only thing remaining is to take the currently playing sound files, combine them, and download them. Here I run into a bit of an issue.

Is there a way to direct soundfiles to a new soundfile instead of (or in addition to) the audio card?

**Comment by therewasaguy** [comment]
Ah, yes! Checkout p5.SoundRecorder http://p5js.org/reference/#/p5.SoundRecorder 

When you tell your recorder to record, you can pass in a p5.SoundFile and it'll write the result to that soundfile's buffer, like this:

```    recorder.record(soundFile); ```


You can also download like this

```    save(soundFile, 'mySound.wav');```

Lemme know if that doesnt do what you're tryna do, and it sounds like a cool project, curious to check it out if it's online!

**Comment by therewasaguy** [comment]
...just thinking, to record multiple sources, you might want to use a p5.Gain as a mixer, and then set that as the input to the recorder

**Comment by Alynva** [comment]
@therewasaguy I tried differents things to record from multiple sources (files) and in all of results the audio appear a quietly slow, like if the process's rate is lower than the audio's rate. I started using the [code](https://github.com/CodingTrain/website/tree/1173167f0e3a9905b6c9db57d3a7efde01c5e67c/Tutorials/P5JS/p5.js_sound/17.11_FFT) of [CodingTrain's video](https://www.youtube.com/watch?v=2O3nm0Nvbi4).

Can this be a slowness of my computer or what?

**Comment by Ramkumar92** [comment]
@therewasaguy I have the same requirement now. I want to record audio along with audio being played out. What is the 2020 way to do it?
