### ISSUE TITLE
AudioVoice setADSR() method

### ISSUE THREAD

**Issue by KevinGrajeda** [processing/p5.js-sound#705]
PolySynth is designed to work with an AudioVoice array, but it calls `setADSR()` on the voices, and `setADSR()` is not an audiovoice method.

<details><summary>examples</summary>
<p>

https://github.com/processing/p5.js-sound/blob/4bbe4ef0455219112360f52246ff385ca220bcc4/src/polysynth.js#L181-L185
https://github.com/processing/p5.js-sound/blob/4bbe4ef0455219112360f52246ff385ca220bcc4/src/polysynth.js#L207-L211
</p>
</details>

so shouldn't AudioVoice have a setADSR() method? such as the `play()`, `triggerAttack()`, `triggerRelease()` and `amp()` methods

https://github.com/processing/p5.js-sound/blob/4bbe4ef0455219112360f52246ff385ca220bcc4/src/audioVoice.js#L18-L24

**Comment by davepagurek** [comment]
It looks like right now only the subclasses of `AudioVoice` have that method, e.g.: https://github.com/processing/p5.js-sound/blob/5bad8cbf3bd1f94d07d7854dec7a6379180a41d5/src/monosynth.js#L297

I think it can make sense to have a default stub implementation like the ones above, just so it's clear when implementing any future `AudioVoice` subclasses that we need to implement that method.

**Comment by KevinGrajeda** [comment]
And I think all the `Audiovoice` methods  need documentation, so that you can implement a subclass without reading the source code.
