### ISSUE TITLE
loadsound in preload not working

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-sound#72]
Examples that call loadSound() in preload stopped working since the recent update to preload in p5. It looks like this has the fix https://github.com/processing/p5.js/commit/a98c4cf4e384fd1247ddc26e2a8a727206dc0fd0

**Comment by therewasaguy** [comment]
Update: that's not the fix

**Comment by lmccart** [comment]
sorry about that, I think this most recent patch should fix it.

**Comment by therewasaguy** [comment]
thank you @lmccart !
