### ISSUE TITLE
`Panner.js` class needs work

### ISSUE THREAD

**Issue by KevinGrajeda** [processing/p5.js-sound#723]
Related to #303
the `Panner.js` class needs some work and documentation, but I'd like to read some thoughts on this:

- Since version 14.1, Safari supports `StereoPannerNode`. [(mdn reference)](https://developer.mozilla.org/en-US/docs/Web/API/StereoPannerNode), should we remove this fallback?
https://github.com/processing/p5.js-sound/blob/959de655ca0ad4c9b1e16671f8eab6a8323044de/src/panner.js#L40-L43

- Should the `Panner.js` class extend the `Effect.js` class like `Panner3D.js` does?

**Comment by davepagurek** [comment]
Safari releases feel a little different than other browser releases since one can only upgrade by upgrading one's whole OS, which might not be the best move for all older hardware. Maybe this means it's worth keeping around the fallback, for a little while longer at least? We don't have an established policy on how much browser compatibility we need yet, what do you think?

I think making it extend Effect makes a lot of sense! It has the same input/output interface, and giving it a dry/wet parameter would bring it in line with other effects would be great.

**Comment by KevinGrajeda** [comment]
Yes, I think adding the panner class to the effects would be great, but this comes with a few problems:


- The `Panner` class works by connecting input and output in the constructor
https://github.com/processing/p5.js-sound/blob/aeba38af5974fe800e22f56272ba43edbc0632e1/src/panner.js#L8-L12
Other effects don't work like this, I think the solution is to make this connections in a separate `process()` and `connect()` methods like other effects do and keep the constructor with no arguments, but with that we would also have to change the panner implementation in the `Oscilator` and `SoundFile` classes.
- I wasnt aware of how safari realeases worked, with that in consideration I agree it is worth trying to keep the fallback, but I think this comes with another problem.
When creating the panner using the fallback code, it is necesary to pass the number of channels in the constructor so that p5 knows how to work with the audio (this is not necessary when using the StereoPannerNode).
https://github.com/processing/p5.js-sound/blob/aeba38af5974fe800e22f56272ba43edbc0632e1/src/panner.js#L44
this doesn't matter as for now the panner class is only used internally but if we want to expose the class in the documentation and want to keep the compatibility, we would need to pass the number of channels each time we connect a new input to the panner effect with something like `panner.proccess(src, numInputChannels, pan)` and I dont know if it's worth having to do this only to keep the compatibility.

What do you think is the best way to deal with this? I would like to have your opinion on what to do.

**Comment by davepagurek** [comment]
> I think the solution is to make this connections in a separate process() and connect() methods like other effects do and keep the constructor with no arguments, but with that we would also have to change the panner implementation in the Oscilator and SoundFile classes

I think this makes sense!

> What do you think is the best way to deal with this?

Since for now it's internal it's probably OK to keep its API different.

For a longer term solution: Do you think it would be feasible to only create and connect the splitter when one connects an input to the panner? Right now we only connect output for the most part (with classes without outputs like `FFT` being an exception, with a `setInput` method instead.) But hypothetically we could add a hook for nodes to know they've been connected to, something like:

```js
connect(other) {
  this.output.connect(other.input)
  if (other.onConnect) {
    other.onConnect(this)
  }
}

onConnect(newInput) {
  // Optionally do something with `newInput`.
  // For panner, this could mean recreating and connecting
  // a splitter based on the input's number of channels
}
```

**Comment by KevinGrajeda** [comment]
I think adding a hook for when a node is connected is a great solution.

If I understood correctly to add this hook we have to add something like this to every connect function we have, right?
```javascript
if (other.onConnect) {
  other.onConnect(this)
}
```


And I think this hook should be something like `_onNewInput()` so that in the future we can add an `onConnect(callback)` method for the users to be able to add their own callback function.
```javascript

onConnect(callback) {
  this._onConnect = callback;
}

_onNewInput(newInput) {
  // Optionally do something with `newInput`.
  this._onConnect();
}
```

**Comment by davepagurek** [comment]
> If I understood correctly to add this hook we have to add something like this to every connect function we have, right?

Right, and ideally the more things extend base classes, the less duplication of this we'll need eventually.

> And I think this hook should be something like _onNewInput() so that in the future we can add an onConnect(callback) method for the users to be able to add their own callback function.

Good point! `_onNewInput` sounds good to me.

**Comment by KevinGrajeda** [comment]
I think I found a better solution for the `Panner.js` fallback problem: by having `input.channelCountMode = 'explicit'` on the input gain node, anything we connect to that node should be [up-mixed or down-mixed](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API#up-mixing_and_down-mixing) to stereo and with this we don't have to keep track of the input number of channels.
