### ISSUE TITLE
`_onNewInput()` hook

### ISSUE THREAD

**Issue by KevinGrajeda** [processing/p5.js-sound#737]
As discussed in #723, we want to add an  `_onNewInput()` hook to let nodes know they've been connected to, but to do this, it is necessary to change every `connect()` method.
At the end of each `connect()` we have to add:
```javascript
connect(unit) {
  //  ...
 
  if (unit._onNewInput) {
    unit._onNewInput(this);
  }
}
```
I think the classes that need this change are:

1. `AudioIn.js`
2. `AudioVoice.js`
3. `Effect.js`
4. `Envelope.js`
5. `Gain.js`
6. `MonoSynth.js`
7. `Oscillator.js`
8. `Panner.js`
9. `PolySynth.js`
10. `SoundFile.js`

from p5.js, the `MediaElement.connect()` method can be used with p5-sound objects, so in the future i think we would like to have this change in that method.

`Amplitude.js` also has a `connect()` method but I don't know what its use is so I don't know if it should be changed.
What should be done with these last two classes? and are those all the classes that need the change?

**Comment by davepagurek** [comment]
Thanks for taking the time to find all the times this is called!

I think when we make this change, we can also make a change in p5 updating `MediaElement.connect`. We typically release p5 and p5.sound in one batch, so the newest versions of both will be able to be used at once.

`Amplitude` seems to only have an output as a bug fix according to this: https://github.com/processing/p5.js-sound/blob/main/src/amplitude.js#L97 I guess it needed to be connected to something for Chrome to not totally ignore it? So it's connected to the main sound output but with 0 volume. That 0-volume signal is the one that would be sent in if you try to `connect()` it to anything else, which wouldn't do anything, so I think this method can just be removed.

**Comment by KevinGrajeda** [comment]
And what do you think of having an implementation of this hook in the same PR so that all of this has a purpose? 
I was thinking of adding an  `_onNewInput()` to `FFT.js` so that when something is connected to it via the `connect()` method, it works the same as using `FFT.setInput()`. In `FFT.setInput()` when we connect something, `FFT.js` stops listening to all sound in the sketch:
https://github.com/processing/p5.js-sound/blob/401120dfbb0f9c617262deaffb48465097278cc5/src/fft.js#L143-L154
So I think it makes sense that in  `FFT._onNewInput()` we do the same:
```javascript
_onNewInput(){
  p5sound.fftMeter.disconnect();
}
```

**Comment by davepagurek** [comment]
That sounds good to me!
