### ISSUE TITLE
mobile safari ios8 / ios7

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-sound#74]
re: https://github.com/processing/p5.js/issues/328#issuecomment-148798815

@hems writes:

my sketch is [super simple](http://pastebin.com/raw.php?i=5DgzZatF), just uses sketch.loadSound, sound.rate / sound.play and p5.FFT.

It worked perfectly on chrome android, but on iOS no chance, using iOS 8.

Any ideas? i'm using the latest version from the website ( /*! v0.4.17 October 13, 2015 */ )

**Comment by hems** [comment]
@therewasaguy thanks for moving the thread.

**Comment by therewasaguy** [comment]
Hi @hems, just pushed some updates to the library. Can you give the latest version a shot?

https://github.com/processing/p5.js-sound/blob/master/lib/p5.sound.js

**Comment by hems** [comment]
didn't work on mobile safari, neither on chrome, on my iOS device ( iphone 5S ).

unfortunately i didn't manage to debug and get the error messages //=

**Comment by montoyamoraga** [comment]
closing this issue because too much has changed since then ~
