### ISSUE TITLE
Notch filter

### ISSUE THREAD

**Issue by DaveSprague** [processing/p5.js-sound#741]
If I start with this code: https://p5js.org/reference/#/p5.Filter
which uses the Filter subclass called BandPass, and in place of

filter = new p5.BandPass();

I put:

filter = new p5.Filter('bandpass');

Then is works the same way.  The BandPass subclass is created by calling Filter with the parameter 'bandpass'

But Filter is also supposed to take other filter types including 'notch', which would create a filter that blocks frequencies around a given center frequency.  But when I modify the code to be:

filter = new p5.Filter('notch');

It behaves as though there's not filter at all.

**Comment by KevinGrajeda** [comment]
If you are using the example at https://p5js.org/reference/#/p5.Filter and just changing 
```javascript
filter = new p5.BandPass();
``` 
to 
```javascript
filter = new p5.Filter('notch');
```
I think the problem might be that the `filter.res()` value used in that example is to high to work with a notch filter.
With a notch filter, the greater the resonance value, the smaller the frequency band, so you could try changing the line that sets the resonance from :
```javascript
filter.res(50);
``` 
to 
```javascript
filter.res(1);
```
 to have a wider frequency band and for the filter to become noticeable.
