### ISSUE TITLE
p5.Env example error message

### ISSUE THREAD

**Issue by sunwangshu** [processing/p5.js-sound#79]
http://p5js.org/reference/#/p5.Env

Error message from browser Safari 9.0

Error: error connecting to node: function (a,b,c){if(b=b||0,c=c||0,null==d){d=new Array(j+1);for(var e=0;j+1>e;e++)d[e]=Math.random()}0>a&&(a=-a),0>b&&(b=-b),0>c&&(c=-c);for(var n,o,p,q,r,s=Math.floor(a),t=Math.floor(b),u=Math.floor(c),v=a-s,w=b-t,x=c-u,y=0,z=.5,A=0;k>A;A++){var B=s+(t<<f)+(u<<h);n=m(v),o=m(w),p=d[B&j],p+=n*(d[B+1&j]-p),q=d[B+g&j],q+=n*(d[B+g+1&j]-q),p+=o*(q-p),B+=i,q=d[B&j],q+=n*(d[B+1&j]-q),r=d[B+g&j],r+=n*(d[B+g+1&j]-r),q+=o*(r-q),p+=m(x)*(q-p),y+=p*z,z*=l,s<<=1,v*=2,t<<=1,w*=2,u<<=1,x*=2,v>=1&&(s++,v--),w>=1&&(t++,w--),x>=1&&(u++,x--)}return y}
connectp5.sound.js:2769
connectp5.sound.js:4224
playp5.sound.js:4096
mouseClicked
_onclickp5.min.js:6:5220

**Comment by therewasaguy** [comment]
thanks for the bug report! I will look into it.
