### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by DArshit94** [processing/p5.js-sound#87]
does p5.SoundRecorder api provides support for capturing audio stream from Safari browser's microphone ?

**Comment by therewasaguy** [comment]
Hi @DArshit94, unfortunately Safari doesn't allow access to the microphone yet. The [p5.AudioIn](http://p5js.org/reference/#/p5.AudioIn) (and [createCapture](http://p5js.org/reference/#/p5/createCapture)) rely on the getUserMedia API:

http://caniuse.com/#feat=stream

**Comment by DArshit94** [comment]
Hi @therewasaguy , Thanks for your support. I have checked link that you have provided and now quite sure about support of safari.
